Repository Codecademy/gamut, pull requests merged in 2021-05, with the labels that each got.

#1700 fix: bump tracking package babel-preset-codecademy to latest
  packages/tracking/package.json
Labels: Auto Update, Ship It :shipit:

#1664 feat: added useTrackingIntegrations to tracking package
  packages/tracking/README.md
  packages/tracking/package.json
  packages/tracking/src/__tests__/user.spec.ts
  packages/tracking/src/events/__tests__/track.spec.ts
  packages/tracking/src/events/__tests__/user.spec.ts
  packages/tracking/src/events/index.ts
  packages/tracking/src/events/track.ts
  packages/tracking/src/events/types.ts
  packages/tracking/src/events/user.ts
  packages/tracking/src/index.ts
  packages/tracking/src/integrations/__tests__/conditionallyLoadAnalytics-test.ts
  packages/tracking/src/integrations/__tests__/fetchDestinationsForWriteKey-test.ts
  packages/tracking/src/integrations/__tests__/mapDestinations-test.ts
  packages/tracking/src/integrations/conditionallyLoadAnalytics.ts
  packages/tracking/src/integrations/consent.ts
  packages/tracking/src/integrations/fetchDestinationsForWriteKey.ts
  packages/tracking/src/integrations/index.ts
  packages/tracking/src/integrations/mapDestinations.ts
  packages/tracking/src/integrations/runSegmentSnippet.js
  packages/tracking/src/integrations/types.ts
  packages/tracking/tsconfig.json
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1695 feat(NotificationItem): add support for forum mentions
  packages/gamut-illustrations/src/EmailAt.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
Labels: Ship It :shipit:

#1708 fix: switch tracking 'verbose' type back to boolean
  packages/tracking/src/events/track.ts
Labels: Auto Update, Ship It :shipit:

#1704 feat: add social media icons and update target illustration
  packages/gamut-icons/src/svg/regular/github-outline-icon.svg
  packages/gamut-icons/src/svg/regular/linkedin-outline-icon.svg
  packages/gamut-icons/src/svg/regular/twitter-outline-icon.svg
  packages/gamut-illustrations/src/Target.tsx
  packages/styleguide/stories/Atoms/Icons/constants.tsx
Labels: Ship It :shipit:

#1698 chore: add test files to .npmignores
  packages/gamut-icons/.npmignore
  packages/gamut-illustrations/.npmignore
  packages/gamut-labs/.npmignore
  packages/gamut-styles/.npmignore
  packages/gamut-system/.npmignore
  packages/gamut-tests/.npmignore
  packages/gamut/.npmignore
  packages/tracking/.npmignore
  packages/variance/.npmignore
Labels: Auto Update, Ship It :shipit:

#1691 fix(Props/Dialog/Button): Prop Fixes for Button / Dialog
  packages/gamut-styles/src/variance/config.ts
  packages/gamut-styles/src/variance/props.ts
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/types.ts
  packages/gamut/src/Dialog/index.tsx
Labels: Next Release, Ship It :shipit:

#1658 feat(Box): Migration + Simplification [GM-202]
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
  packages/gamut-labs/src/AppHeader/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/Byline/index.tsx
  packages/gamut-labs/src/CurriculumCard/BottomTag/index.tsx
  packages/gamut-labs/src/CurriculumCard/Difficulty/index.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/gamut-labs/src/GlobalFooter/FooterLegal/MadeIn.tsx
  packages/gamut-labs/src/GlobalFooter/FooterLinks.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
  packages/gamut-labs/src/HubCard/index.tsx
  packages/gamut-labs/src/LandingPage/CTA.tsx
  packages/gamut-labs/src/LandingPage/Description.tsx
  packages/gamut-labs/src/LandingPage/PageFeatures.tsx
  packages/gamut-labs/src/PageSection/index.tsx
  packages/gamut-labs/src/Popover/index.tsx
  packages/gamut/src/Alert/Alert.tsx
  packages/gamut/src/Badge/index.tsx
  packages/gamut/src/Box/Box.tsx
  packages/gamut/src/Box/FlexBox.tsx
  packages/gamut/src/Box/GridBox.tsx
  packages/gamut/src/Box/props.ts
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/Form/FormGroup.tsx
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/GridFormSubmit/index.tsx
  packages/gamut/src/NotificationList/EmptyNotification/index.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/SkipToContent/index.tsx
  packages/gamut/src/Toggle/index.tsx
  packages/styleguide/.storybook/components/Docs/DocsPage.tsx
  packages/styleguide/.storybook/components/Navigation/TableOfContents.tsx
  packages/styleguide/.storybook/components/Scales/ColorScale.tsx
  packages/styleguide/stories/Atoms/Button/examples.tsx
  packages/styleguide/stories/Atoms/FocusTrap.stories.mdx
  packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/Layout.stories.mdx
  packages/styleguide/stories/Foundations/Theme/tables.tsx
  packages/styleguide/stories/Layouts/Box/FlexBox.stories.mdx
  packages/styleguide/stories/Layouts/Box/GridBox.stories.mdx
  packages/styleguide/stories/Layouts/Box/index.stories.mdx
  packages/styleguide/stories/Molecules/Coachmark/Coachmark.examples.tsx
  packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx
Labels: Next Release, Ship It :shipit:

#1693 fix(ListSection): Fixing accessibility and spacing
  packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx
  packages/gamut-labs/src/ListSection/index.tsx
  packages/gamut-labs/src/PageSection/index.tsx
  packages/styleguide/stories/Molecules/ListSection.stories.mdx
Labels: Ship It :shipit:

#1711 chore: bump component-test-setup to v0.3.1
  package.json
  packages/gamut-kit/package.json
  packages/gamut-styles/package.json
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1699 feat: added GlobalPage organism
  packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage-test.tsx
  packages/gamut-labs/src/GlobalPage/index.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut/src/AppWrapper/index.tsx
  packages/styleguide/stories/Organisms/GlobalPage.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1712 fix(LayoutGrid): Add ordered fallback
  packages/gamut/src/Layout/LayoutGrid.tsx
Labels: Ship It :shipit:

#1715 feat(PageWrapper): Extend stacking context reset element for pages with a background color
  packages/gamut-labs/src/GlobalPage/index.tsx
  packages/gamut-styles/src/Background.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/AppWrapper/index.tsx
Labels: Ship It :shipit:

#1716 feat: Add BrowserPuzzle and Python illustrations
  packages/gamut-illustrations/src/BrowserPuzzle.tsx
  packages/gamut-illustrations/src/Python.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Ship It :shipit:

#1706 feat(GridForm): added hidden input functionality
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormHiddenInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/__tests__/stubs.ts
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1652 fix(Select): add aria-hidden to ArrowDownChevron
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Form/Select.tsx
Labels: Auto Update, Ship It :shipit:

#1710 feat: adding icons for Business repo
  packages/gamut-icons/src/svg/regular/analytics-graph-icon.svg
  packages/gamut-icons/src/svg/regular/earth-icon.svg
  packages/gamut-icons/src/svg/regular/monitor-book-icon.svg
  packages/gamut-icons/src/svg/regular/multiple-users-icon.svg
  packages/gamut-icons/src/svg/regular/stacked-squares-icon.svg
Labels: Auto Update, Ship It :shipit:

#1662 feat: SelectDropdown: controlled component + inputProps + docs restructuring
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/SelectDropdown.tsx
  packages/gamut/src/Form/__tests__/Select-test.tsx
  packages/gamut/src/Form/__tests__/SelectDropdown-test.tsx
  packages/gamut/src/Form/utils.tsx
  packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
Labels: Ship It :shipit:

#1707 feat(Icon): Adds system props to all icons [GM-218]
  .circleci/config.yml
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/package.json
  packages/gamut-icons/src/props.ts
  packages/gamut-icons/src/types.ts
  packages/gamut-icons/svgr.config.js
  packages/gamut-icons/tsconfig.json
  packages/gamut/src/Alert/Alert.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/styleguide/stories/Atoms/Button/examples.tsx
  packages/styleguide/stories/Atoms/Button/index.stories.mdx
Labels: Ship It :shipit:

#1654 feat!: add new gamut-patterns package
  jest.config.js
  packages/gamut-patterns/.gitignore
  packages/gamut-patterns/.npmignore
  packages/gamut-patterns/README.md
  packages/gamut-patterns/__tests__/patterns-test.tsx
  packages/gamut-patterns/babel.config.js
  packages/gamut-patterns/package.json
  packages/gamut-patterns/src/index.tsx
  packages/gamut-patterns/src/patterns/checker/CheckerDense.tsx
  packages/gamut-patterns/src/patterns/checker/CheckerLoose.tsx
  packages/gamut-patterns/src/patterns/checker/CheckerRegular.tsx
  packages/gamut-patterns/src/patterns/checker/index.tsx
  packages/gamut-patterns/src/patterns/diagonalA/DiagonalADense.tsx
  packages/gamut-patterns/src/patterns/diagonalA/DiagonalALoose.tsx
  packages/gamut-patterns/src/patterns/diagonalA/DiagonalARegular.tsx
  packages/gamut-patterns/src/patterns/diagonalA/index.tsx
  packages/gamut-patterns/src/patterns/diagonalB/DiagonalBDense.tsx
  packages/gamut-patterns/src/patterns/diagonalB/DiagonalBLoose.tsx
  packages/gamut-patterns/src/patterns/diagonalB/DiagonalBRegular.tsx
  packages/gamut-patterns/src/patterns/diagonalB/index.tsx
  packages/gamut-patterns/src/patterns/dot/DotDense.tsx
  packages/gamut-patterns/src/patterns/dot/DotLoose.tsx
  packages/gamut-patterns/src/patterns/dot/DotRegular.tsx
  packages/gamut-patterns/src/patterns/dot/index.tsx
  packages/gamut-patterns/src/patterns/ex/ExDense.tsx
  packages/gamut-patterns/src/patterns/ex/ExLoose.tsx
  packages/gamut-patterns/src/patterns/ex/ExRegular.tsx
  packages/gamut-patterns/src/patterns/ex/index.tsx
  packages/gamut-patterns/src/patterns/flower/FlowerDense.tsx
  packages/gamut-patterns/src/patterns/flower/FlowerLoose.tsx
  packages/gamut-patterns/src/patterns/flower/FlowerRegular.tsx
  packages/gamut-patterns/src/patterns/flower/index.tsx
  packages/gamut-patterns/src/patterns/grid/GridDense.tsx
  packages/gamut-patterns/src/patterns/grid/GridLoose.tsx
  packages/gamut-patterns/src/patterns/grid/GridRegular.tsx
  packages/gamut-patterns/src/patterns/grid/index.tsx
  packages/gamut-patterns/src/patterns/herringbone/Herringbone.tsx
  packages/gamut-patterns/src/patterns/herringbone/index.tsx
  packages/gamut-patterns/src/patterns/rain/RainDense.tsx
  packages/gamut-patterns/src/patterns/rain/RainLoose.tsx
  packages/gamut-patterns/src/patterns/rain/RainRegular.tsx
  packages/gamut-patterns/src/patterns/rain/index.tsx
  packages/gamut-patterns/src/patterns/stripe/StripeDense.tsx
  packages/gamut-patterns/src/patterns/stripe/StripeLoose.tsx
  packages/gamut-patterns/src/patterns/stripe/StripeRegular.tsx
  packages/gamut-patterns/src/patterns/stripe/index.tsx
  packages/gamut-patterns/src/types.ts
  packages/gamut-patterns/tsconfig.json
  packages/styleguide/.storybook/main.ts
  packages/styleguide/stories/Atoms/Patterns.stories.mdx
Labels: Ship It :shipit:

#1690 feat!: bump eslint-config packages to latest
  .circleci/config.yml
  .eslintrc.js
  package.json
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/rules/typescript.js
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1709 feat(footer): Hackathon egg for learn page footer
  packages/gamut-labs/src/GlobalFooter/FooterLegal/MadeIn.tsx
  packages/gamut-labs/src/GlobalFooter/FooterLegal/__tests__/MadeIn-test.tsx
  packages/gamut-labs/src/GlobalFooter/FooterLegal/index.tsx
  packages/gamut-labs/src/GlobalFooter/index.tsx
Labels: Ship It :shipit:

#1724 feat(Alert/Banner): Adds ColorModes for backwards compatibility and uses most recent props [GM-224]
  packages/gamut/src/Alert/Alert.tsx
  packages/gamut/src/Alert/variants.tsx
  packages/gamut/src/Banner/index.tsx
  packages/styleguide/stories/Molecules/Alert/constants.tsx
Labels: Ship It :shipit:

#1733 feat(ListSection): Updating ListSection to have a ShowAll/ShowLess click handler prop
  packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx
  packages/gamut-labs/src/ListSection/index.tsx
Labels: Ship It :shipit:

#1731 chore(deps): Emotion Dependency clean up
  package.json
  packages/gamut-icons/package.json
  packages/gamut-illustrations/package.json
  packages/gamut-labs/package.json
  packages/gamut-patterns/package.json
  packages/gamut-styles/package.json
  packages/gamut-system/package.json
  packages/gamut/package.json
  packages/styleguide/package.json
  packages/variance/package.json
  yarn.lock
Labels: Ship It :shipit:

#1727 feat: added error page contents for 500 errors
  packages/gamut-labs/src/ErrorContents/__tests__/ErrorContents-test.tsx
  packages/gamut-labs/src/ErrorContents/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/ErrorContents.stories.mdx
Labels: Ship It :shipit:

#1728 fix: disable react/jsx-one-expression-per-line rule
  packages/eslint-config/index.js
  packages/gamut-labs/src/ErrorContents/__tests__/ErrorContents-test.tsx
  packages/gamut-labs/src/ErrorContents/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/ErrorContents.stories.mdx
Labels: Ship It :shipit:

#1732 docs(Input): Fixes input documentation
  packages/styleguide/stories/Atoms/FormInputs/Input.stories.mdx
Labels: Ship It :shipit:

#1649 chore(ProgressBar): ProgressBar to variance API
  packages/gamut/src/ProgressBar/index.tsx
  packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1742 fix(Input): cursor weirdness
  packages/gamut/src/Form/SelectDropdown.tsx
  packages/gamut/src/Form/styles/shared.tsx
Labels: Ship It :shipit:

#1743 feat: disabled consistent-return ESLint rule
  packages/eslint-config/index.js
Labels: Ship It :shipit:

#1744 fix(Select): add labels back
  packages/gamut/src/Form/utils.tsx
Labels: Ship It :shipit:

#1750 style(CurriculumCard): Capitalize text prop
  packages/gamut-labs/src/CurriculumCard/index.tsx
Labels: Ship It :shipit:

#1753 test: Add deterministic snapshot to option formatting
  packages/gamut/src/Form/__tests__/__snapshots__/utils-test.tsx.snap
  packages/gamut/src/Form/__tests__/utils-test.tsx
Labels: Ship It :shipit:

#1745 feat(Header)!: reroute header upsell for upgrade
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
  packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1705 feat: added EmptySection
  packages/gamut-labs/src/EmptySection/__tests__/EmptySection-test.tsx
  packages/gamut-labs/src/EmptySection/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/EmptySection.stories.mdx
Labels: Ship It :shipit:

#1746 fix(Input): fixed hidden field empty spaces
  packages/gamut/src/Form/Input.tsx
Labels: Ship It :shipit:

#1761 feat(Popover): use theme.colors.secondary for outline color
  packages/gamut-icons/src/svg/mini/mini-kebab-menu-icon.svg
  packages/gamut-labs/src/Popover/index.tsx
  packages/styleguide/stories/Molecules/Popover/index.stories.mdx
Labels: Ship It :shipit:

#1764 feat: add illustration for empty section
  packages/gamut-illustrations/src/Hills.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Ship It :shipit:

#1766 fix: remove DropdownButton animation and add offset props
  packages/gamut-labs/src/DropdownButton/index.tsx
Labels: Ship It :shipit:

#1765 feat: added data-testid for GlobalPage's PageWrapper
  packages/gamut-labs/src/GlobalPage/index.tsx
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/AppWrapper/index.tsx
Labels: Ship It :shipit:

#1767 fix: add shouldForwardProp to DropdownButton
  packages/gamut-labs/src/DropdownButton/index.tsx
Labels: Ship It :shipit:

#1773 fix: allow override of tooltip alignment
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut/src/Form/FormGroupLabel.tsx
Labels: Ship It :shipit:

#1747 feat!: prepended OneTrust to tracking integrations loads
  packages/tracking/README.md
  packages/tracking/package.json
  packages/tracking/src/index.ts
  packages/tracking/src/integrations/index.ts
  packages/tracking/src/integrations/onetrust.ts
  packages/tracking/src/integrations/types.ts
Labels: Ship It :shipit:

#1763 refactor(Modal)!: Deprecating Modal component
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Dialog/__tests__/Dialog-test.tsx
  packages/gamut/src/Interstitial/index.tsx
  packages/gamut/src/ModalDeprecated/__tests__/Modal-test.tsx
  packages/gamut/src/ModalDeprecated/index.tsx
  packages/gamut/src/ModalDeprecated/styles.module.scss
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/stories/Atoms/FocusTrap.stories.mdx
  packages/styleguide/stories/Atoms/Overlay.stories.mdx
  packages/styleguide/stories/Molecules/Dialog.stories.mdx
  packages/styleguide/stories/Molecules/ModalDeprecated.stories.mdx
Labels: Ship It :shipit:

#1777 feat: Make Dialog body a <div>
  packages/gamut/src/Dialog/__tests__/Dialog-test.tsx
  packages/gamut/src/Dialog/index.tsx
Labels: Ship It :shipit:

#1780 fix: GridForm Sweet Container - add missing label
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSweetContainerInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/types.ts
Labels: Ship It :shipit:

#1776 feat: add Keyhole illustration
  packages/gamut-illustrations/src/Keyhole.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Ship It :shipit:

#1758 fix: Use native focus-visible in addition to polyfill
  packages/gamut-styles/src/cache/stylisPlugins/focusVisible.ts
Labels: Ship It :shipit:

#1775 feat: add Kebab type to DropdownButton
  packages/gamut-labs/src/DropdownButton/__tests__/DropdownButton-test.tsx
  packages/gamut-labs/src/DropdownButton/index.tsx
Labels: Ship It :shipit:

#1779 fix(GridForm): add optional Cancel button
  packages/gamut/src/GridForm/GridFormButtons/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1782 fix: Fix Storybook crashes caused by circular object references on uncalled Icon components
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
  packages/gamut-icons/svgr.config.js
  packages/styleguide/package.json
  packages/styleguide/stories/Atoms/Overlay.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeader.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1783 feat: Migrate final gamut-system docs + functions to variance [WEB-1413]
  .circleci/config.yml
  README.md
  packages/gamut-illustrations/package.json
  packages/gamut-kit/package.json
  packages/gamut-labs/package.json
  packages/gamut-labs/src/DropdownButton/index.tsx
  packages/gamut-labs/src/EmptySection/index.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
  packages/gamut-labs/src/LandingPage/types.tsx
  packages/gamut-labs/src/LandingPage/variants.tsx
  packages/gamut-patterns/package.json
  packages/gamut-styles/package.json
  packages/gamut-styles/src/index.ts
  packages/gamut-styles/src/props.ts
  packages/gamut-styles/src/utilities/index.ts
  packages/gamut-styles/src/utilities/shouldForwardProp.ts
  packages/gamut-styles/src/variance/index.ts
  packages/gamut-styles/src/variance/props.ts
  packages/gamut/src/Alert/Alert.tsx
  packages/gamut/src/Alert/variants.tsx
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/ContentContainer/index.tsx
  packages/gamut/src/DeprecatedCard/CardShell.tsx
  packages/gamut/src/Dialog/index.tsx
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Layout/Column.tsx
  packages/gamut/src/ProLabel/index.tsx
  packages/gamut/src/ProgressBar/index.tsx
  packages/gamut/src/ToolTip/index.tsx
  packages/gamut/src/Typography/Text.tsx
  packages/styleguide/.storybook/addons/system/components/Elements.tsx
  packages/styleguide/.storybook/components/DataTable/elements.tsx
  packages/styleguide/.storybook/components/Docs/StatusIndicator.tsx
  packages/styleguide/.storybook/main.ts
  packages/styleguide/stories/Foundations/System/About.stories.mdx
  packages/styleguide/stories/Foundations/System/Variants.stories.mdx
Labels: Ship It :shipit:

#1788 feat(GridForm): Allow ReactNode for GridForm Radio label
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1781 feat(GridForm): add placeholder field for TextArea in GridForm
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1793 fix: SkipToContent z :(
  packages/gamut/src/SkipToContent/index.tsx
Labels: Ship It :shipit:

#1794 fix: Set region and label on STC
  packages/gamut/src/SkipToContent/index.tsx
Labels: Ship It :shipit:
