Repository Codecademy/gamut, pull requests merged in 2021-03, with the labels that each got.

#1440 fix(popover): provide fallbackFocus
  packages/gamut-labs/src/experimental/Popover/index.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/index.stories.mdx
Labels: Ship It :shipit:

#1428 fix: use sm columns in xs viewports by default for GridForm
  packages/gamut/src/GridForm/index.tsx
Labels: Auto Update, Ship It :shipit:

#1436 feat(Variance): Experimental MVP for internal use
  jest.config.js
  packages/variance/.gitignore
  packages/variance/.npmignore
  packages/variance/README.md
  packages/variance/babel.config.js
  packages/variance/package.json
  packages/variance/src/__tests__/component-test.tsx
  packages/variance/src/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/index.tsx
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
  packages/variance/src/types/props.ts
  packages/variance/src/types/utils.ts
  packages/variance/src/utils/propNames.ts
  packages/variance/src/utils/responsive.ts
  packages/variance/tsconfig.json
  yarn.lock
Labels: Ship It :shipit:

#1434 feat(props): Adds custom shouldForwardProp to omit system props
  packages/gamut-labs/src/experimental/Text/index.tsx
  packages/gamut-styles/src/system.ts
  packages/gamut/src/Box/Box.tsx
  packages/styleguide/.storybook/addons/system/propMeta.ts
Labels: Auto Update, Ship It :shipit:

#1450 fix(Styleguide): Fixes destructuring for argtype enhances
  packages/styleguide/.storybook/components/PropsTable/constants.ts
Labels: Ship It :shipit:

#1452 refactor(NotificationItemNew): fix typo on aria label on single notification delete icon
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
Labels: Ship It :shipit:

#1457 fix(global header): export global header types
  packages/gamut-labs/src/experimental/index.ts
Labels: Ship It :shipit:

#1461 build: Set ^4.0.0 for version of lodash peer dependency
  packages/gamut-system/package.json
Labels: Ship It :shipit:

#1459 style(tracking): expand page event tracking type
  packages/tracking/src/types.ts
Labels: Ship It :shipit:

#1462 feat: deprecated useBreakpoint and friends
  packages/gamut-labs/src/lib/breakpointHooks/index.ts
Labels: Auto Update, Ship It :shipit:

#1463 feat: LocationPinIcon
  packages/gamut-icons/src/svg/regular/location-pin-icon.svg
Labels: Ship It :shipit:

#1453 feat(StackingContext): Adds consistent reset for root nodes [WEB-1329]
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/AppWrapper/index.tsx
  packages/gamut/src/BodyPortal/index.tsx
  packages/gamut/src/index.tsx
Labels: Ship It :shipit:

#1444 feat(ThemeProvider): Adds GamutThemeProvider component and initial Global styles
  packages/gamut-styles/src/index.ts
  packages/gamut-styles/src/theme/GamutThemeProvider.tsx
  packages/gamut-styles/src/theme/index.ts
  packages/gamut-styles/src/theme/props.ts
  packages/gamut-styles/src/theme/theme.tsx
  packages/gamut-styles/src/theme/utils/createThemeVariables.ts
  packages/gamut-styles/src/theme/utils/createVariables.ts
  packages/gamut-styles/src/theme/utils/shouldForwardProp.ts
  packages/gamut-styles/src/variables/elements.ts
  packages/gamut-styles/src/variables/index.ts
  packages/gamut-styles/src/variables/responsive.ts
  packages/gamut-tests/src/index.tsx
  packages/styleguide/.storybook/addons/system/enhancers.ts
  packages/styleguide/.storybook/addons/system/propMeta.ts
  packages/styleguide/.storybook/components/PropsTable/constants.ts
  packages/styleguide/.storybook/decorators/theme.tsx
Labels: Ship It :shipit:

#1412 feat(Alert)!: New Visual Identity Alert [GM-119]
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Alert/Alert.tsx
  packages/gamut/src/Alert/__tests__/Alert-test.tsx
  packages/gamut/src/Alert/constants.tsx
  packages/gamut/src/Alert/index.tsx
  packages/gamut/src/Alert/styles.module.scss
  packages/gamut/src/Alert/types.ts
  packages/gamut/src/Truncate/index.tsx
  packages/styleguide/stories/Molecules/Alert.stories.mdx
  packages/styleguide/stories/Molecules/Alert/constants.ts
  packages/styleguide/stories/Molecules/Alert/index.stories.mdx
Labels: Ship It :shipit:

#1465 feat!: Create Gamut-kit
  packages/gamut-kit/README.md
  packages/gamut-kit/package.json
Labels: Ship It :shipit:

#1467 fix(styles): Run emotion plugin
  packages/gamut-styles/babel.config.js
Labels: Ship It :shipit:

#1468 fix!: Update dependencies to latest
  packages/gamut-kit/package.json
Labels: Ship It :shipit:

#1442 feat(HubCard): Created a new hub page card component
  packages/gamut-labs/src/experimental/HubCard/index.tsx
  packages/gamut-labs/src/experimental/index.ts
  packages/styleguide/stories/Brand/Atoms/HubCard.stories.mdx
Labels: Ship It :shipit:

#1471 chore(docs): add instructions for npm-link-better
  README.md
Labels: Ship It :shipit:

#1469 style(GlobalHeader): Use theme variable for header height
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
Labels: Ship It :shipit:

#1466 fix(global header): add support for user role "account manager"
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1470 feat(NotificationItemNew): map notif type to icon if no image url provided
  packages/gamut-illustrations/src/Bell.tsx
  packages/gamut-illustrations/src/Megaphone.tsx
  packages/gamut-illustrations/src/New.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut/src/NotificationList/typings.ts
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1482 style(HubCard): Updated title font weight
  packages/gamut-labs/src/experimental/HubCard/index.tsx
Labels: Ship It :shipit:

#1474 feat(SkipToContent): SkipToContent + SkipToContent target visual identity + emotion [GM-158] [EGG-701]
  packages/gamut-icons/src/svg/mini/mini-arrow-down-icon.svg
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/SkipToContent/__tests__/SkipToContent-test.tsx
  packages/gamut/src/SkipToContent/index.tsx
  packages/gamut/src/SkipToContent/styles.module.scss
  packages/styleguide/stories/Atoms/SkipToContent.stories.mdx
Labels: Ship It :shipit:

#1472 feat(Icons): Adds new icons for Form updates
  packages/gamut-icons/src/svg/mini/mini-info-outline-icon.svg
  packages/gamut-icons/src/svg/regular/amex-icon.svg
  packages/gamut-icons/src/svg/regular/credit-card-icon.svg
  packages/gamut-icons/src/svg/regular/mastercard-icon.svg
  packages/gamut-icons/src/svg/regular/view-off-icon.svg
  packages/gamut-icons/src/svg/regular/visa-icon.svg
  packages/styleguide/stories/Atoms/Icons/constants.tsx
Labels: Ship It :shipit:

#1445 fix: Replace focus-trap with focus-lock-on
  packages/gamut-labs/package.json
  packages/gamut-labs/src/experimental/Popover/index.tsx
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/package.json
  packages/gamut/src/FocusTrap/__tests__/FocusTrap-test.tsx
  packages/gamut/src/FocusTrap/index.tsx
  packages/gamut/src/Modal/index.tsx
  packages/gamut/src/Overlay/__tests__/Overlay-test.tsx
  packages/gamut/src/Overlay/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/stories/Atoms/FocusTrap.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Molecules/Modal.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1477 feat(Global Header): add redirect parameter
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/experimental/AppHeader/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/__tests__/urlHelpers-test.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/urlHelpers.tsx
Labels: Ship It :shipit:

#1484 feat(GlobalHeader): Add pro paused and trial completed header types
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1488 docs: update readme to include gamut-kit version
  README.md
Labels: Ship It :shipit:

#1487 refactor(Quote): use Emotion and variants for dark/light theme
  packages/gamut-labs/src/brand/Quote/__tests__/Quote-test.tsx
  packages/gamut-labs/src/brand/Quote/index.tsx
  packages/gamut-labs/src/brand/Quote/styles.module.scss
  packages/gamut-labs/src/brand/Testimonial/index.tsx
  packages/styleguide/stories/Brand/Atoms/Quote.stories.mdx
Labels: Ship It :shipit:

#1493 fix(Modal): add aria-label prop
  packages/gamut/src/Modal/index.tsx
Labels: Ship It :shipit:

#1473 feat(GridForm): Add tooltip to gridform fields
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormToolTipWrapper/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFromToolTip/__tests__/GridFormToolTip-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFromToolTip/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1430 feat(GlobalHeader): header animation on scroll
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/styles.module.scss
  packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
  packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1507 fix(NotificationItemNew): tracking fix & accessibility improvement
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
Labels: Ship It :shipit:

#1489 fix(Card)!: Animation Fixes and Gamut migration
  packages/gamut-labs/src/experimental/Card/index.tsx
  packages/gamut-labs/src/experimental/Card/shadow.ts
  packages/gamut-labs/src/experimental/HubCard/index.tsx
  packages/gamut-labs/src/experimental/index.ts
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/DeprecatedCard/CardBody.tsx
  packages/gamut/src/DeprecatedCard/CardButton/index.tsx
  packages/gamut/src/DeprecatedCard/CardButton/styles.module.scss
  packages/gamut/src/DeprecatedCard/CardContent/index.tsx
  packages/gamut/src/DeprecatedCard/CardContent/styles.module.scss
  packages/gamut/src/DeprecatedCard/CardEyebrow/index.tsx
  packages/gamut/src/DeprecatedCard/CardEyebrow/styles.module.scss
  packages/gamut/src/DeprecatedCard/CardFooter.tsx
  packages/gamut/src/DeprecatedCard/CardHeader/index.tsx
  packages/gamut/src/DeprecatedCard/CardHeader/styles.module.scss
  packages/gamut/src/DeprecatedCard/CardShell.tsx
  packages/gamut/src/DeprecatedCard/CardStack/index.tsx
  packages/gamut/src/DeprecatedCard/CardStack/styles.module.scss
  packages/gamut/src/DeprecatedCard/index.tsx
  packages/gamut/src/DeprecatedCard/styles/CardBody.module.scss
  packages/gamut/src/DeprecatedCard/styles/CardFooter.module.scss
  packages/gamut/src/DeprecatedCard/styles/CardShell.module.scss
  packages/gamut/src/DeprecatedCard/styles/utils.scss
  packages/gamut/src/Modal/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/components/PropsTable/constants.ts
  packages/styleguide/stories/Atoms/Card.stories.mdx
Labels: Ship It :shipit:

#1486 style(Anchor): Adds new anchor variants and styles necessary for usage [GM-159] [GM-160]
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/landingPage/__tests__/Hero-test.tsx
  packages/gamut-labs/src/landingPage/__tests__/VideoGallery-test.tsx
  packages/gamut-styles/core/_typography.scss
  packages/gamut-styles/utils/variables/_typography.scss
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/ButtonDeprecatedBase/index.tsx
  packages/gamut/src/Markdown/__tests__/Markdown-test.tsx
  packages/gamut/src/Markdown/libs/overrides/MarkdownAnchor/__tests__/MarkdownAnchor-test.tsx
  packages/gamut/src/Markdown/libs/overrides/MarkdownAnchor/index.tsx
  packages/styleguide/.storybook/decorators/theme.tsx
  packages/styleguide/stories/Typography/Anchor.stories.mdx
Labels: Ship It :shipit:

#1509 ci: block PRs until automerge label is added, other ci cleanup
  .circleci/config.yml
  .github/reviewers.yml
  .github/workflows/automerge.yml
  .github/workflows/required-labels.yml
Labels: Ship It :shipit:

#1503 feat(NotificationItemNew): add new forum notification icons
  packages/gamut-illustrations/src/ChatBox.tsx
  packages/gamut-illustrations/src/Envelope.tsx
  packages/gamut-illustrations/src/Heart.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1514 fix(NotificationItemNew): dismiss icon hover
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1392 feat(ContentContainer)!: update responsive padding
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-styles/src/variables/spacing.ts
  packages/gamut/src/AppBar/index.tsx
  packages/gamut/src/AppBar/styles/index.module.scss
  packages/gamut/src/ContentContainer/__tests__/ContentContainer-test.tsx
  packages/gamut/src/ContentContainer/index.tsx
  packages/gamut/src/ContentContainer/styles.module.scss
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/styleguide/stories/Layouts/ContentContainer.stories.mdx
Labels: Ship It :shipit:

#1527 docs: corrected FAQ phrasing around external contributors
  packages/styleguide/stories/Meta/FAQs.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1171 chore(deps): dependency updates
  babel.config.js
  package.json
  packages/gamut-icons/package.json
  packages/gamut-illustrations/package.json
  packages/gamut-labs/package.json
  packages/gamut-styles/package.json
  packages/gamut-system/package.json
  packages/gamut-tests/package.json
  packages/gamut/package.json
  packages/markdown-overrides/package.json
  packages/variance/package.json
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1528 chore(deps): dependencies
  .github/workflows/pr-title.yml
  packages/babel-preset-codecademy/package.json
  packages/styleguide/package.json
  packages/tracking/package.json
  yarn.lock
Labels: Ship It :shipit:

#1409 refactor!: converted ToolTip to Emotion
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/gamut/src/ToolTip/__tests__/ToolTip-test.tsx
  packages/gamut/src/ToolTip/index.tsx
  packages/gamut/src/ToolTip/styles.module.scss
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
  packages/styleguide/stories/Atoms/TooltipArea.tsx
Labels: Auto Update, Ship It :shipit:

#1510 docs(FormGroups): FormGroups + FormGroupLabel
  packages/gamut/src/Form/FormGroup.tsx
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/__tests__/FormGroup-test.tsx
  packages/styleguide/stories/Atoms/FormElements/FormGroup.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/FormGroupLabel.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
Labels: Ship It :shipit:

#1555 feat(FormDescription): it is now navy
  packages/gamut/src/Form/styles/FormGroupDescription.module.scss
Labels: Ship It :shipit:

#1494 feat(Dialog): Add new Dialog Modal component [GM-18]
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Dialog/__tests__/Dialog-test.tsx
  packages/gamut/src/Dialog/index.tsx
  packages/gamut/src/Modal/index.tsx
  packages/gamut/src/index.tsx
  packages/macros/lib/title.macro.js
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/stories/Molecules/Dialog.stories.mdx
  packages/styleguide/stories/Molecules/Modal.stories.mdx
Labels: Next Release

#1542 feat(Markdown): allow generated heading ids [CET-617]
  packages/gamut/src/Markdown/__tests__/Markdown-test.tsx
  packages/gamut/src/Markdown/index.tsx
  packages/gamut/src/Markdown/libs/sanitizationConfig.ts
Labels: Auto Update, Next Release, Ship It :shipit:

#1504 feat(GamutProvider): Adds single provider for Theme + Cache + Globals + Assets [WEB-1352] [GM-173]
  package.json
  packages/gamut-labs/README.md
  packages/gamut-styles/package.json
  packages/gamut-styles/src/AssetProvider.tsx
  packages/gamut-styles/src/GamutProvider.tsx
  packages/gamut-styles/src/globals/Reboot.tsx
  packages/gamut-styles/src/globals/Typography.tsx
  packages/gamut-styles/src/globals/index.tsx
  packages/gamut-styles/src/index.ts
  packages/gamut-styles/src/props.ts
  packages/gamut-styles/src/remoteAssets/fonts.ts
  packages/gamut-styles/src/styles/boxShadow.ts
  packages/gamut-styles/src/styles/fontSmoothing.ts
  packages/gamut-styles/src/styles/index.ts
  packages/gamut-styles/src/styles/noSelect.ts
  packages/gamut-styles/src/styles/pxRem.ts
  packages/gamut-styles/src/styles/responsive.ts
  packages/gamut-styles/src/styles/screenReaderOnly.ts
  packages/gamut-styles/src/theme.ts
  packages/gamut-styles/src/theme/GamutThemeProvider.tsx
  packages/gamut-styles/src/theme/index.ts
  packages/gamut-styles/src/utilities/createThemeVariables.ts
  packages/gamut-styles/src/utilities/createVariables.ts
  packages/gamut-styles/src/utilities/index.ts
  packages/gamut-styles/src/utilities/shouldForwardProp.ts
  packages/gamut-styles/src/variables/shadows.ts
  packages/gamut-styles/src/variables/spacing.ts
  packages/gamut-styles/src/variables/typography.ts
  packages/gamut-tests/src/index.tsx
  packages/gamut/README.md
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/styleguide/.storybook/addons/system/propMeta.ts
  packages/styleguide/.storybook/components/Page/index.tsx
  packages/styleguide/.storybook/components/PropsTable/constants.ts
  packages/styleguide/.storybook/decorators/styles.scss
  packages/styleguide/.storybook/decorators/theme.tsx
  packages/styleguide/.storybook/decorators/wrapper.ts
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/.storybook/theme.ts
  packages/styleguide/package.json
  yarn.lock
Labels: Next Release, Ship It :shipit:

#1556 ci: fix PR coverage issues due to parallelism
  .circleci/config.yml
  codecov.yml
Labels: Ship It :shipit:

#1499 chore(ButtonDeprecated): Dead Code removal - unused themes [GM-166]
  packages/gamut/src/AccordionButton/index.tsx
  packages/gamut/src/ButtonDeprecated/index.tsx
  packages/gamut/src/ButtonDeprecated/styles/variables.scss
  packages/styleguide/stories/Atoms/ButtonDeprecated/helpers.tsx
  packages/styleguide/stories/Atoms/ButtonDeprecated/index.stories.mdx
Labels: Auto Update, Next Release, Ship It :shipit:

#1513 feat(Input): Add custom gamut-icons to Input components
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/__tests__/Input-test.tsx
  packages/gamut/src/Form/styles/shared.tsx
  packages/styleguide/stories/Atoms/FormInputs/Input.stories.mdx
Labels: Next Release, Ship It :shipit:

#1506 refactor(FormLabel): move tooltip from GridForm to FormLabel
  packages/gamut/src/Form/FormGroup.tsx
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormToolTipWrapper/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFromToolTip/__tests__/GridFormToolTip-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFromToolTip/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Atoms/FormElements/FormGroup.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1559 refactor(Alert): Adding InlineAlertType
  packages/gamut/src/Alert/Alert.tsx
Labels: Ship It :shipit:

#1563 chore: remove redundant react-anonymous-display-name in Babel configs
  packages/gamut-icons/babel.config.js
  packages/gamut-labs/babel.config.js
  packages/gamut/babel.config.js
  packages/markdown-overrides/babel.config.js
  packages/styleguide/.storybook/babel.config.js
Labels: Auto Update, Ship It :shipit:

#1557 feat: add DeleteFilledIcon
  packages/gamut-icons/src/svg/regular/delete-filled-icon.svg
Labels: Ship It :shipit:

#1496 feat: add height animation to dropdown
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
Labels: Ship It :shipit:

#1564 fix(Alerts): Add more Y padding for inline alerts (multiline looks weird) [GM-189]
  packages/gamut/src/Alert/Alert.tsx
Labels: Ship It :shipit:

#1565 chore(Docs): Add deprecations and consolidate molecules / orgs
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut/src/Accordion/index.tsx
  packages/gamut/src/AccordionArea/index.tsx
  packages/gamut/src/AccordionButton/index.tsx
  packages/gamut/src/ButtonDeprecated/index.tsx
  packages/gamut/src/ButtonDeprecatedBase/index.tsx
  packages/gamut/src/DeprecatedCard/CardBody.tsx
  packages/gamut/src/DeprecatedCard/CardContent/index.tsx
  packages/gamut/src/DeprecatedCard/CardEyebrow/index.tsx
  packages/gamut/src/DeprecatedCard/CardFooter.tsx
  packages/gamut/src/DeprecatedCard/CardHeader/index.tsx
  packages/gamut/src/DeprecatedCard/CardShell.tsx
  packages/gamut/src/DeprecatedCard/CardStack/index.tsx
  packages/gamut/src/FlexBox/Container.tsx
  packages/gamut/src/FlexBox/Item.tsx
  packages/gamut/src/FlexGrid/Col.tsx
  packages/gamut/src/FlexGrid/FlexGrid.tsx
  packages/gamut/src/FlexGrid/Row.tsx
  packages/gamut/src/HighlightedText/index.tsx
  packages/gamut/src/Menus/MenuItem/index.tsx
  packages/gamut/src/Menus/SideMenu/index.tsx
  packages/gamut/src/Modal/index.tsx
  packages/gamut/src/NotificationList/NotificationIcon.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/NotificationList/index.tsx
  packages/gamut/src/RadialProgress/index.tsx
  packages/gamut/src/SplitInterstitial/index.tsx
  packages/gamut/src/Tabs/Tab/index.tsx
  packages/gamut/src/Tabs/TabList/index.tsx
  packages/gamut/src/Tabs/TabPanel/index.tsx
  packages/gamut/src/Tabs/Tabs/index.tsx
  packages/gamut/src/Typography/Heading.tsx
  packages/gamut/src/Typography/Text.tsx
  packages/styleguide/stories/Atoms/RadialProgress.stories.mdx
  packages/styleguide/stories/Layouts/FlexContainer.stories.mdx
  packages/styleguide/stories/Layouts/FlexGrid.stories.mdx
  packages/styleguide/stories/Molecules/Accordion.stories.mdx
  packages/styleguide/stories/Molecules/AccordionButton.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/About.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeader.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderDropdown.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderLink.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderLinkMobile.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderLogo.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderMainMenuMobile.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderMobile.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/AppHeaderSubMenuMobile.stories.mdx
  packages/styleguide/stories/Molecules/AppHeader/MockAppHeaderElements.tsx
  packages/styleguide/stories/Molecules/Coachmark/Coachmark.examples.tsx
  packages/styleguide/stories/Molecules/Coachmark/index.stories.mdx
  packages/styleguide/stories/Molecules/Header.stories.mdx
  packages/styleguide/stories/Molecules/Interstitial.stories.mdx
  packages/styleguide/stories/Molecules/Modal.stories.mdx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
  packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Molecules/Popover/index.stories.mdx
  packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
  packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1566 docs: add kit installation explanation and guide
  README.md
Labels: Ship It :shipit:

#1571 fix: pattern should have aria-hidden
  packages/gamut/src/Pattern/index.tsx
Labels: Ship It :shipit:

#1560 chore(Dependencies): Upgrade TS / RHF to enable `themed` function [WEB-1370] [WEB-1371] [GM-191]
  package.json
  packages/gamut-styles/src/utilities/__tests__/themed-test.ts
  packages/gamut-styles/src/utilities/index.ts
  packages/gamut-styles/src/utilities/themed.ts
  packages/gamut/package.json
  packages/gamut/src/Form/FormGroup.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/variance/package.json
  yarn.lock
Labels: Ship It :shipit:

#1568 feat(Text): Deprecate Text / Heading and add more robust UI Text Component [GM-162]
  packages/gamut-system/src/props/flex.ts
  packages/gamut-system/src/props/layout.ts
  packages/gamut-system/src/props/position.ts
  packages/gamut-system/src/props/typography.ts
  packages/gamut-system/src/types/properties.ts
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/ProgressBar/index.tsx
  packages/gamut/src/Typography/HeadingDeprecated.tsx
  packages/gamut/src/Typography/Text.tsx
  packages/gamut/src/Typography/TextDeprecated.tsx
  packages/gamut/src/Typography/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Atoms/CardDeprecated.stories.mdx
  packages/styleguide/stories/Atoms/Markdown/examples.tsx
  packages/styleguide/stories/Atoms/Markdown/index.stories.mdx
  packages/styleguide/stories/Foundations/Colors/index.stories.mdx
  packages/styleguide/stories/Molecules/SplitInterstitial/index.stories.mdx
  packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
  packages/styleguide/stories/Typography/HeadingDeprecated.stories.mdx
  packages/styleguide/stories/Typography/Text.stories.mdx
  packages/styleguide/stories/Typography/TextDeprecated.stories.mdx
Labels: Ship It :shipit:

#1573 feat(Variance): Static CSS Methods `css` and `variant` [WEB-1116]
  packages/variance/package.json
  packages/variance/src/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/transforms/parseSize.ts
  packages/variance/src/types/config.ts
  packages/variance/src/types/props.ts
  packages/variance/src/utils/__tests__/propNames-test.ts
  packages/variance/src/utils/propNames.ts
Labels: Ship It :shipit:

#1575 chore(deps): Don't update emotion version
  packages/variance/package.json
Labels: Ship It :shipit:

#1570 feat: new @codecademy/tsconfig package
  packages/gamut-icons/__tests__/icons-test.tsx
  packages/tsconfig/CHANGELOG.md
  packages/tsconfig/README.md
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.json
  tsconfig.json
Labels: Auto Update, Ship It :shipit:

#1574 fix(NotificationListNew): remove top pattern
  packages/gamut/src/NotificationListNew/index.tsx
Labels: Ship It :shipit:

#1576 feat(Variance): `css` - Standard CSS Property Passthrough + Selector System Props [WEB-1117]
  packages/variance/src/__tests__/component-test.tsx
  packages/variance/src/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/types/config.ts
  packages/variance/src/types/props.ts
  packages/variance/src/utils/getStaticProperties.ts
Labels: Ship It :shipit:

#1577 feat(Variance): base => _ for un scoped style [WEB-1381]
  packages/variance/src/__tests__/component-test.tsx
  packages/variance/src/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/types/props.ts
  packages/variance/src/utils/responsive.ts
Labels: Ship It :shipit:

#1578 feat(Variance): Use only the global emotion theme type (Stage 5: Acceptance) [WEB-1382]
  packages/variance/__tests__/__fixtures__/theme.ts
  packages/variance/__tests__/component-test.tsx
  packages/variance/__tests__/tsconfig.json
  packages/variance/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/tsconfig.json
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
  packages/variance/src/types/props.ts
  packages/variance/src/types/theme.ts
  packages/variance/src/utils/responsive.ts
  packages/variance/tsconfig.base.json
  packages/variance/tsconfig.json
Labels: Ship It :shipit:
