Repository Codecademy/gamut, pull requests merged in 2021-01, with the labels that each got.

#1269 fix(Markdown): prevent re-renders caused by default prop
  packages/gamut/src/Markdown/index.tsx
Labels: Ship It :shipit:

#1270 fix(IconButton): make children prop optional
  packages/gamut/src/Button/IconButton.tsx
Labels: Ship It :shipit:

#1268 feat(Anchor): add variants to anchor
  packages/gamut-labs/src/experimental/index.ts
  packages/gamut/src/Anchor/index.tsx
  packages/styleguide/stories/Core/Typography/Anchor.stories.mdx
Labels: Ship It :shipit:

#1272 fix(toggle): aria-label typo
  packages/gamut/src/Toggle/index.tsx
Labels: Ship It :shipit:

#1273 fix: added fontSmoothing to buttons
  packages/gamut/src/Button/ButtonInner.tsx
Labels: Ship It :shipit:

#1249 feat(Icons): Add video player movie icon
  packages/gamut-icons/src/svg/video-player-movie-icon.svg
  packages/gamut-illustrations/src/HomeOffice.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Auto Update, Ship It :shipit:

#1275 feat(tracking): Add a fullstory boolean to TrackingOptions type
  packages/tracking/src/types.ts
Labels: Ship It :shipit:, review me

#1282 feat(tool): Adding a report*.json to .gitignore
  .gitignore
Labels: Auto Update, Ship It :shipit:

#1284 fix(Overlay): Body overflow hidden iOS bug
  packages/gamut/src/Overlay/__tests__/Overlay-test.tsx
  packages/gamut/src/Overlay/index.tsx
  packages/gamut/src/Overlay/styles.module.scss
Labels: Ship It :shipit:

#1280 refactor: Converting from SCSS to emotion for Form and GridForm components
  packages/gamut/src/Form/Checkbox.tsx
  packages/gamut/src/Form/__tests__/Checkbox-test.tsx
  packages/gamut/src/Form/_variables.ts
  packages/gamut/src/Form/styles/Checkbox.module.scss
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/styles.module.scss
  packages/gamut/src/GridForm/GridFormSubmit/index.tsx
  packages/gamut/src/GridForm/GridFormSubmit/styles.module.scss
Labels: Auto Update, Ship It :shipit:

#1288 fix(macros): Fixes regex syntax
  packages/macros/__tests__/__snapshots__/macros.test.js.snap
  packages/macros/lib/title.macro.js
Labels: Auto Update, Ship It :shipit:

#1267 feat(Interstitial): add focus mgmt to Interstitial
  packages/gamut/src/Interstitial/index.tsx
  packages/gamut/src/Interstitial/styles.module.scss
  packages/styleguide/stories/Molecules/Interstitial.stories.mdx
Labels: Ship It :shipit:

#1290 chore(Styleguide): Deprecate addon-knobs GM-138
  packages/styleguide/.storybook/main.ts
  packages/styleguide/.storybook/manager.ts
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/package.json
  packages/styleguide/stories/Atoms/ButtonDeprecated/index.stories.mdx
  packages/styleguide/stories/Atoms/CardDeprecated.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs.stories.mdx
  packages/styleguide/stories/Atoms/HiddenText.stories.mdx
  packages/styleguide/stories/Atoms/HighlightedText.stories.mdx
  packages/styleguide/stories/Atoms/Icons/constants.tsx
  packages/styleguide/stories/Atoms/Icons/index.stories.mdx
  packages/styleguide/stories/Atoms/InputStepper.stories.mdx
  packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx
  packages/styleguide/stories/Atoms/RadialProgress.stories.mdx
  packages/styleguide/stories/Atoms/SkipToContent.stories.mdx
  packages/styleguide/stories/Atoms/Spinner.stories.mdx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
  packages/styleguide/stories/Brand/Atoms/Avatar.stories.mdx
  packages/styleguide/stories/Brand/Atoms/Loading.stories.mdx
  packages/styleguide/stories/Brand/Atoms/Logo.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageFeaturesSection.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PagePrefooter.stories.mdx
  packages/styleguide/stories/Layouts/LayoutGrid.stories.mdx
  packages/styleguide/stories/Meta/Stories.stories.mdx
  packages/styleguide/stories/Molecules/Accordion.stories.mdx
  packages/styleguide/stories/Molecules/AccordionButton.stories.mdx
  packages/styleguide/stories/Molecules/Alert.stories.mdx
  packages/styleguide/stories/Molecules/Banner.stories.mdx
  packages/styleguide/stories/Molecules/Header.stories.mdx
  packages/styleguide/stories/Molecules/Interstitial.stories.mdx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
  packages/styleguide/stories/Molecules/SplitInterstitial/index.stories.mdx
  packages/styleguide/stories/Molecules/Tabs/index.stories.mdx
  packages/styleguide/stories/Molecules/Truncate.stories.mdx
  packages/styleguide/stories/Molecules/Video.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1291 feat(Styleguide): Adds VScode snippets for new stories GM-137
  .vscode/settings.json
  .vscode/stories.code-snippets
Labels: Auto Update, Ship It :shipit:

#1294 fix(Storybook): Update meta links to storybooks standard color
  packages/styleguide/.storybook/components/Page/index.tsx
Labels: Ship It :shipit:

#1298 fix(Checkbox): Remove overwritten data-testids on checkboxes
  packages/gamut/src/Form/Checkbox.tsx
Labels: Ship It :shipit:

#1302 docs: typo in focus copy
  packages/styleguide/stories/Molecules/Interstitial.stories.mdx
Labels: Ship It :shipit:

#1301 fix(styleguide): Enable no jsx-no-undef on mdx
  packages/eslint-config/index.js
  packages/styleguide/stories/Atoms/ButtonDeprecated/index.stories.mdx
  packages/styleguide/stories/Atoms/Overlay.stories.mdx
  packages/styleguide/stories/Foundations/Typography.stories.mdx
  packages/styleguide/stories/Molecules/Accordion.stories.mdx
  packages/styleguide/stories/Molecules/Modal.stories.mdx
  packages/styleguide/stories/Molecules/SplitInterstitial/index.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1304 fix: landing page descriptions margin-top adjustments
  packages/gamut-labs/src/landingPage/Description.tsx
  packages/gamut-labs/src/landingPage/Feature.tsx
Labels: Ship It :shipit:

#1308 fix(styles): Default button focus styles to focus-visible
  packages/gamut-styles/core/_reboot.scss
Labels: Auto Update, Ship It :shipit:

#1296 chore(ESLinter): Adding rule for stylesheet names
  .eslintrc.js
  packages/eslint-config/index.js
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/styles.module.scss
Labels: Auto Update, Ship It :shipit:

#1297 feat(docs): Refresh story writing meta docs
  packages/styleguide/stories/Meta/Stories.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1316 fix(Checkbox): Fixes :checked + :disabled styles
  packages/gamut/src/Form/Checkbox.tsx
Labels: Ship It :shipit:

#1315 feat(styleguide): Storybook config clean up
  packages/styleguide/.storybook/assets/logo.svg
  packages/styleguide/.storybook/components/Page/index.tsx
  packages/styleguide/.storybook/components/PropsTable/Elements.tsx
  packages/styleguide/.storybook/components/PropsTable/index.tsx
  packages/styleguide/.storybook/components/PropsTable/useSystemProps.ts
  packages/styleguide/.storybook/components/TableOfContents/Section.tsx
  packages/styleguide/.storybook/components/TableOfContents/elements.tsx
  packages/styleguide/.storybook/components/TableOfContents/index.tsx
  packages/styleguide/.storybook/components/TableOfContents/utils.tsx
  packages/styleguide/.storybook/decorators/emotion.tsx
  packages/styleguide/.storybook/decorators/theme.tsx
  packages/styleguide/.storybook/main.ts
  packages/styleguide/.storybook/manager.ts
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/.storybook/theme.ts
  packages/styleguide/tsconfig.json
Labels: Ship It :shipit:

#1317 docs(FormInputs): Creates individual pages for FormInputs
  .vscode/stories.code-snippets
  packages/gamut/src/Form/Checkbox.tsx
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/Radio.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/TextArea.tsx
  packages/styleguide/.storybook/components/Page/index.tsx
  packages/styleguide/stories/Atoms/FormDecorations.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/About.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/Form.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/FormError.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/FormGroup.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/FormGroupDescription.stories.mdx
  packages/styleguide/stories/Atoms/FormElements/FormGroupLabel.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/About.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/Checkbox.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/Input.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/RadioGroup.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/TextArea.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1276 fix: re-add accordion animation
  packages/gamut/src/AccordionArea/index.tsx
  packages/gamut/src/AccordionArea/styles.module.scss
  packages/styleguide/stories/Molecules/Accordion.stories.mdx
Labels: Ship It :shipit:

#1325 feat: add 3-video gallery component
  packages/gamut-labs/src/landingPage/PageVideoGallery.tsx
  packages/gamut-labs/src/landingPage/__tests__/VideoGallery-test.tsx
  packages/gamut-labs/src/landingPage/index.ts
  packages/gamut/src/Video/index.tsx
  packages/styleguide/stories/Brand/Organisms/PageVideoGallery.stories.mdx
Labels: Ship It :shipit:

#1314 docs: documented breaking changes release process
  README.md
Labels: Auto Update, Ship It :shipit:

#1334 fix: scr => src
  packages/styleguide/stories/Brand/Atoms/Avatar.stories.mdx
Labels: Ship It :shipit:

#1311 feat(Toggle)!: refactor to emotion and add focus styles
  packages/gamut/src/Toggle/index.tsx
  packages/gamut/src/Toggle/styles/index.module.scss
  packages/styleguide/.storybook/addons/system/enhancers.ts
  packages/styleguide/.storybook/decorators/Emotion.tsx
  packages/styleguide/.storybook/decorators/emotion.tsx
  packages/styleguide/stories/Atoms/Toggle.stories.mdx
Labels: Ship It :shipit:

#1329 fix(Truncate): Fix truncation markup and makes props more flexible
  packages/gamut/package.json
  packages/gamut/src/Alert/__tests__/Alert-test.tsx
  packages/gamut/src/Alert/index.tsx
  packages/gamut/src/Truncate/__tests__/Truncate-test.tsx
  packages/gamut/src/Truncate/index.tsx
  packages/gamut/src/Truncate/styles.module.scss
  yarn.lock
Labels: Ship It :shipit:

#1339 fix(Alert): Prevent JS test loop for line defaults
  packages/gamut/src/Alert/__tests__/Alert-test.tsx
  packages/gamut/src/Alert/index.tsx
  packages/styleguide/stories/Molecules/Alert.stories.mdx
Labels: Ship It :shipit:

#1338 fix: used useIsomorphicLayoutEffect instead of useLayoutEffect
  packages/gamut/src/AccordionArea/index.tsx
  packages/gamut/src/Overlay/index.tsx
Labels: Auto Update, Ship It :shipit:

#1341 fix: guard against undefined body in Overlay
  packages/gamut/src/Overlay/index.tsx
Labels: Auto Update, Ship It :shipit:

#1323 feat(PageHero)!: added functionality for PageHero to take images or videos as props
  packages/gamut-labs/src/landingPage/PageHero.tsx
  packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
  packages/gamut-labs/src/landingPage/__tests__/Hero-test.tsx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
Labels: Ship It :shipit:

#1331 docs: Update props JSDOC (A-K) for Gamut-Labs
  packages/gamut-labs/src/brand/Avatar/index.tsx
  packages/gamut-labs/src/brand/Byline/index.tsx
  packages/gamut-labs/src/brand/Header/HeaderContainer/index.tsx
  packages/styleguide/stories/Brand/Atoms/Avatar.stories.mdx
  packages/styleguide/stories/Molecules/Header.stories.mdx
Labels: Ship It :shipit:

#1260 feat(Styleguide): Add specific theme and scale docs
  packages/gamut-styles/src/utilities/boxShadow.ts
  packages/gamut-styles/src/variables/shadows.ts
  packages/styleguide/.storybook/addons/system/enhancers.ts
  packages/styleguide/.storybook/addons/system/propMeta.ts
  packages/styleguide/.storybook/components/Box.tsx
  packages/styleguide/.storybook/components/ColorScale/index.tsx
  packages/styleguide/.storybook/components/DataTable/elements.tsx
  packages/styleguide/.storybook/components/DataTable/index.tsx
  packages/styleguide/.storybook/components/MarkdownElements.tsx
  packages/styleguide/.storybook/components/Page/index.tsx
  packages/styleguide/.storybook/components/TableOfContents/elements.tsx
  packages/styleguide/.storybook/components/index.tsx
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/stories/Foundations/Colors/index.stories.mdx
  packages/styleguide/stories/Foundations/Theme/index.stories.mdx
  packages/styleguide/stories/Foundations/Theme/tables.tsx
  packages/styleguide/tsconfig.json
Labels: Ship It :shipit:
