Repository Codecademy/gamut, pull requests merged in 2021-06, with the labels that each got.

#1797 fix(variance): Fix static css mutability for `css` [GM-235]
  packages/variance/integration/__tests__/component-test.tsx
  packages/variance/src/core.ts
Labels: Ship It :shipit:

#1796 feat(GridForm): rowspan fields
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/stubs.ts
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Next Release

#1800 fix: Filter non forwardable props on icons
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
Labels: Next Release

#1798 fix: ButtonContainer should grow to fit its parent [GM-238]
  packages/gamut/src/Button/ButtonInner.tsx
Labels: Next Release

#1762 refactor: Input, TextArea, FormGroupLabel + Select to system props
  packages/gamut-styles/src/styles/index.ts
  packages/gamut-styles/src/styles/transitionConcat.ts
  packages/gamut-styles/src/variables/timing.ts
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/SelectDropdown.tsx
  packages/gamut/src/Form/TextArea.tsx
  packages/gamut/src/Form/_variables.ts
  packages/gamut/src/Form/styles/shared-system-props.tsx
  packages/gamut/src/Form/styles/shared.tsx
Labels: Next Release

#1792 feat: add custom-group to GridForm
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/types.ts
Labels: Next Release

#1771 style(Subtitle): fixed lesson count bug when count is 0
  packages/gamut-labs/src/CurriculumCard/Subtitle/__tests__/Subtitle-test.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
Labels: Next Release, Ship It :shipit:

#1789 feat(themes): add editor colors to platform theme
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/themes/platform.ts
Labels: Next Release, Ship It :shipit:

#1757 fix(Anchor): Allow Cards to be hovered inside Anchors [GM-236]
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Card/index.tsx
  packages/styleguide/stories/Atoms/Card.stories.mdx
Labels: Next Release

#1787 fix(EmptySection): fix spacing issues
  packages/gamut-labs/src/EmptySection/index.tsx
  packages/styleguide/stories/Molecules/EmptySection.stories.mdx
Labels: Next Release

#1801 feat!: release -kit-4.7
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
  packages/gamut-labs/src/CurriculumCard/Subtitle/__tests__/Subtitle-test.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
  packages/gamut-labs/src/EmptySection/index.tsx
  packages/gamut-styles/src/styles/index.ts
  packages/gamut-styles/src/styles/transitionConcat.ts
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/themes/platform.ts
  packages/gamut-styles/src/utilities/themed.ts
  packages/gamut-styles/src/variables/timing.ts
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/SelectDropdown.tsx
  packages/gamut/src/Form/TextArea.tsx
  packages/gamut/src/Form/_variables.ts
  packages/gamut/src/Form/styles/shared-system-props.tsx
  packages/gamut/src/Form/styles/shared.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/stubs.ts
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Atoms/Card.stories.mdx
  packages/styleguide/stories/Molecules/EmptySection.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1802 feat(theme prop description): Adds descriptive text to theme prop
  packages/styleguide/.storybook/addons/system/enhancers.ts
Labels: Ship It :shipit:

#1807 fix: custom-group
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1804 feat(icons): Adds LE trophy and certificate filled icons
  packages/gamut-icons/src/svg/regular/discount-star-premium-filled-icon.svg
  packages/gamut-icons/src/svg/regular/trophy-filled-icon.svg
  packages/styleguide/stories/Atoms/Icons/constants.tsx
Labels: Ship It :shipit:

#1808 fix(GlobalPage): extending bg color to whole page height
  packages/gamut-labs/src/GlobalPage/index.tsx
Labels: Ship It :shipit:

#1803 refactor: GlobalFooter and GlobalHeader
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
Labels: Ship It :shipit:

#1812 fix: Google and App store
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Ship It :shipit:

#1770 docs: added SkipToContent section to GlobalPage story
  packages/styleguide/stories/Organisms/GlobalPage.stories.mdx
Labels: Ship It :shipit:

#1814 feat: add SocialMediaSharing component
  .eslintrc.js
  packages/gamut-labs/src/SocialMediaSharing/SocialShareIconLink.tsx
  packages/gamut-labs/src/SocialMediaSharing/__tests__/SocialMediaSharing-test.tsx
  packages/gamut-labs/src/SocialMediaSharing/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/SocialMediaSharing.stories.mdx
Labels: Ship It :shipit:

#1811 feat(GridFormRadioGroupInput): Can use a ReactNode for labels
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/__tests__/GridFormRadioGroupInput-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/types.ts
Labels: Ship It :shipit:

#1805 feat: Add AvatarChooser component
  package.json
  packages/gamut-labs/src/Avatar/index.tsx
  packages/gamut-labs/src/Avatar/styles.module.scss
  packages/gamut-labs/src/AvatarChooser/__tests__/AvatarChooser-test.tsx
  packages/gamut-labs/src/AvatarChooser/index.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut/src/Form/FormError.tsx
  packages/styleguide/stories/Brand/Molecules/AvatarChooser.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1813 chore: Sunset FlexGrid
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/FlexGrid/Col.tsx
  packages/gamut/src/FlexGrid/FlexGrid.tsx
  packages/gamut/src/FlexGrid/Row.tsx
  packages/gamut/src/FlexGrid/index.tsx
  packages/gamut/src/FlexGrid/styles/index.module.scss
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Layouts/FlexGrid.stories.mdx
Labels: Next Release

#1819 feat(variance): states boolean toggle styles GM-233
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/gamut-labs/src/Popover/index.tsx
  packages/gamut-styles/src/variance/props.ts
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Box/Box.tsx
  packages/gamut/src/Box/FlexBox.tsx
  packages/gamut/src/Box/GridBox.tsx
  packages/gamut/src/Box/props.ts
  packages/gamut/src/FlexGrid/Col.tsx
  packages/gamut/src/FlexGrid/FlexGrid.tsx
  packages/gamut/src/FlexGrid/Row.tsx
  packages/gamut/src/FlexGrid/index.tsx
  packages/gamut/src/FlexGrid/styles/index.module.scss
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/addons/system/propMeta.ts
  packages/styleguide/stories/Foundations/System/Variants.stories.mdx
  packages/styleguide/stories/Layouts/Box/FlexBox.stories.mdx
  packages/styleguide/stories/Layouts/FlexGrid.stories.mdx
  packages/variance/integration/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/types/config.ts
Labels: Next Release, Ship It :shipit:

#1768 fix: Turn on global style color aliases [GM-242]
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/__tests__/Background-test.tsx
  packages/gamut-styles/src/globals/Reboot.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
Labels: Next Release

#1720 feat(FloatingCard): Add FloatingCard add it to Dialog GM-182
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Dialog/index.tsx
  packages/gamut/src/FloatingCard/FloatingCard.tsx
  packages/gamut/src/Toast/Toast.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Atoms/FloatingCard.stories.mdx
  packages/styleguide/stories/Molecules/Dialog.stories.mdx
  packages/styleguide/stories/Molecules/Toast.stories.mdx
Labels: Next Release, Ship It :shipit:

#1820 feat: Navy scale + color alias changes GM-237
  packages/gamut-labs/src/Avatar/index.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/__tests__/Background-test.tsx
  packages/gamut-styles/src/globals/Reboot.tsx
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/themes/core.ts
  packages/gamut-styles/src/themes/platform.ts
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut/src/Form/styles/shared-system-props.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/variance/src/createTheme/createTheme.test.ts
  packages/variance/src/createTheme/createTheme.ts
  packages/variance/src/createTheme/index.ts
  packages/variance/src/createTheme/types.ts
  packages/variance/src/utils/flattenScale.ts
  packages/variance/src/utils/serializeTokens.ts
Labels: Next Release, Ship It :shipit:

#1817 feat(tracking): Record the page referrer for every event.
  packages/tracking/src/events/track.ts
  packages/tracking/src/events/types.ts
Labels: Auto Update, Ship It :shipit:

#1816 fix: blur ToolTip target on escape key down
  packages/gamut/src/ToolTip/index.tsx
Labels: Next Release, Ship It :shipit:

#1824 fix(AvatarChooser): Add alt text to Avatar image
  packages/gamut-labs/src/AvatarChooser/__tests__/AvatarChooser-test.tsx
  packages/gamut-labs/src/AvatarChooser/index.tsx
Labels: Ship It :shipit:

#1815 fix: clear errors on input change in GridForm
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/__tests__/GridFormTextInput-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/GridForm/types.ts
Labels: Ship It :shipit:

#1736 feat: enable @typescript-eslint/prefer-optional-chain
  packages/eslint-config/index.js
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/AvatarChooser/index.tsx
  packages/gamut/src/Markdown/libs/overrides/index.tsx
  packages/gamut/src/Markdown/libs/preprocessing.ts
Labels: Ship It :shipit:

#1825 fix: Fix story link scrolling and breadcrumbs spacing
  packages/styleguide/.storybook/components/Docs/DocsContainer.tsx
  packages/styleguide/.storybook/components/Docs/DocsPage.tsx
  packages/styleguide/.storybook/components/Navigation/BreadCrumbs.tsx
Labels: Ship It :shipit:

#1826 fix: DocContainer Types
  packages/styleguide/.storybook/components/Docs/DocsContainer.tsx
Labels: Ship It :shipit:

#1831 fix: revert "fix: clear errors on input change in GridForm"
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCustomInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/__tests__/GridFormTextInput-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__fixtures__/renderers.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/GridForm/types.ts
Labels: Ship It :shipit:

#1806 refactor: Radio buttons
  packages/gamut/src/Form/Radio.tsx
  packages/gamut/src/Form/__tests__/Radio-test.tsx
  packages/gamut/src/Form/__tests__/RadioGroup-test.tsx
  packages/gamut/src/Form/styles/Radio.module.scss
  packages/gamut/src/Form/styles/shared-system-props.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
Labels: Ship It :shipit:

#1835 docs(GridForm): dedupe ids + names
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1827 feat(props): Support `color` and other HTML attributes as system props without type collision GM-247
  packages/gamut-icons/__tests__/icons-test.tsx
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
  packages/gamut-icons/src/types.ts
  packages/gamut-icons/svgr.config.js
  packages/gamut-labs/src/DropdownButton/index.tsx
  packages/gamut-labs/src/EmptySection/index.tsx
  packages/gamut-patterns/__tests__/patterns-test.tsx
  packages/gamut-patterns/src/types.ts
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/variance/config.ts
  packages/gamut-styles/src/variance/utils.ts
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Banner/index.tsx
  packages/gamut/src/Box/Box.tsx
  packages/gamut/src/Box/FlexBox.tsx
  packages/gamut/src/Box/GridBox.tsx
  packages/gamut/src/Box/props.ts
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/Dialog/index.tsx
  packages/gamut/src/FloatingCard/FloatingCard.tsx
  packages/gamut/src/Form/FormError.tsx
  packages/gamut/src/Layout/Column.tsx
  packages/gamut/src/Layout/LayoutGrid.tsx
  packages/gamut/src/Logo/shared.tsx
  packages/gamut/src/Pattern/index.tsx
  packages/gamut/src/ProLabel/index.tsx
  packages/gamut/src/Toast/Toast.tsx
  packages/gamut/src/Typography/Text.tsx
Labels: Next Release, Ship It :shipit:

#1836 fix: ErrorSpan - switch to initial variant
  packages/gamut/src/Form/FormError.tsx
Labels: Ship It :shipit:

#1822 fix(GlobalHeader): fix transparent header when refreshing scrolled SSR'd page
  packages/gamut-labs/src/GlobalHeader/index.tsx
Labels: Ship It :shipit:

#1740 feat(Flyout):
  packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
  packages/gamut-labs/src/Flyout/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/Flyout.stories.mdx
Labels: Ship It :shipit:

#1784 feat(LayoutMenu): Creates LayoutMenu using Flyout and Accordions
  packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
  packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
  packages/gamut-labs/src/LayoutMenu/SectionItemLink.tsx
  packages/gamut-labs/src/LayoutMenu/SelectedSectionItem.tsx
  packages/gamut-labs/src/LayoutMenu/__tests__/AccordionMenu-test.tsx
  packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenu-test.tsx
  packages/gamut-labs/src/LayoutMenu/index.ts
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Organisms/LayoutMenu.stories.mdx
Labels: Ship It :shipit:

#1829 feat(Text): Add more common utility variants / states as props GM-248
  packages/gamut/src/Box/props.ts
  packages/gamut/src/Typography/Text.tsx
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
  packages/variance/src/types/props.ts
Labels: Ship It :shipit:

#1809 feat(Buttons): Color + Structure Redux [GM-237]
  packages/gamut-icons/src/types.ts
  packages/gamut-labs/src/LandingPage/types.tsx
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/themes/core.ts
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Box/Box.tsx
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/CTAButton.tsx
  packages/gamut/src/Button/FillButton.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/StrokeButton.tsx
  packages/gamut/src/Button/TextButton.tsx
  packages/gamut/src/Button/index.ts
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/Button/types.ts
  packages/gamut/src/Button/variants.ts
  packages/gamut/src/ButtonBase/ButtonBase.tsx
  packages/gamut/src/ButtonBase/__tests__/ButtonOutline-test.tsx
  packages/gamut/src/GridForm/GridFormButtons/index.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
Labels: Auto Update, Next Release, Ship It :shipit:

#1791 feat(variance): Computed styles, and configurable CSSType narrowing [GM-233]
  packages/gamut-styles/src/variance/index.ts
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/DeprecatedCard/CardShell.tsx
  packages/variance/integration/__fixtures__/theme.ts
  packages/variance/integration/__tests__/variance-test.ts
  packages/variance/src/index.ts
  packages/variance/src/scales/createScale.ts
  packages/variance/src/types/config.ts
Labels: Ship It :shipit:

#1842 fix: fix Layout wording for SM sizes
  packages/styleguide/stories/Foundations/Layout.stories.mdx
Labels: Ship It :shipit:

#1844 fix: Hover + Shadow regression
  packages/gamut-styles/src/themes/__tests__/__snapshots__/theme-test.ts.snap
  packages/gamut-styles/src/themes/core.ts
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/ButtonBase/ButtonBase.tsx
  packages/gamut/src/Card/index.tsx
  packages/gamut/src/DeprecatedCard/CardShell.tsx
Labels: Ship It :shipit:

#1845 feat(GlobalFooter): Update href of 'Beta Content' link to point at hub page
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
Labels: Ship It :shipit:

#1840 fix(LayoutMenu): update focus visible states and x-button placement
  packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
  packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
  packages/gamut-labs/src/LayoutMenu/SectionItemLink.tsx
Labels: Ship It :shipit:

#1850 fix(Radio): fix background color
  packages/gamut/src/Form/styles/shared-system-props.tsx
  packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx
Labels: Ship It :shipit:

#1851 fix(Flyout): Move Close Icon Placement
  packages/gamut-labs/src/Flyout/index.tsx
Labels: Ship It :shipit:

#1852 fix(LayoutMenu): Emotion Only GM-258
  packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
Labels: Ship It :shipit:

#1858 fix: prevent Radio label from getting squished
  packages/gamut/src/Form/styles/shared-system-props.tsx
Labels: Ship It :shipit:

#1857 feat(tracking): Added repo-tracking to user events
  packages/tracking/src/events/types.ts
Labels: Ship It :shipit:

#1843 feat(Icons): Custom root element and default aria-hidden
  packages/gamut-icons/__tests__/icons-test.tsx
  packages/gamut-icons/emotion-plugin.js
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
  packages/gamut-icons/svgr.config.js
Labels: Ship It :shipit:

#1834 fix: sweet containers should not cause scroll on tab
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSweetContainerInput/index.tsx
Labels: Auto Update, Ship It :shipit:

#1859 fix(ProLabel): add title
  packages/gamut/src/ProLabel/index.tsx
Labels: Ship It :shipit:

#1862 fix(Icons): Fix default size 16
  packages/gamut-icons/src/props.ts
  packages/gamut-icons/svgr.config.js
Labels: Ship It :shipit:

#1861 feat(GlobalHeader): adding referral link
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
Labels: Ship It :shipit:

#1866 fix: ToolTip icons can't be aria-hidden
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#1869 fix: Icon titleId and Size Defaults
  packages/gamut-icons/icon-template.js
  packages/gamut-icons/src/props.ts
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#1870 fix: FormGroupLabel Tooltip
  packages/gamut/src/Form/FormGroupLabel.tsx
Labels: Ship It :shipit:

#1838 fix(Input): add aria-hidden for to Input icons
  packages/gamut/src/Form/Input.tsx
Labels: Ship It :shipit:

#1872 feat: add lock and networkUser icons for shareable sandbox
  packages/gamut-icons/src/svg/regular/lock-1-icon.svg
  packages/gamut-icons/src/svg/regular/network-user-icon.svg
Labels: Ship It :shipit:

#1865 feat(AppHeader types): Updating AppHeaderItem types
  jest.config.js
  packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/AppHeader/__tests__/AppHeader-test.tsx
  packages/gamut-labs/src/DropdownButton/__tests__/DropdownList-test.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
Labels: Ship It :shipit:

#1863 feat: add idSuffix prop to Pattern
  packages/gamut/src/Pattern/__tests__/Pattern-test.tsx
  packages/gamut/src/Pattern/defs.tsx
  packages/gamut/src/Pattern/index.tsx
Labels: Auto Update, Ship It :shipit:

#1868 feat: enable non-nullable-type-assertion-style
  packages/eslint-config/index.js
  packages/gamut/src/GridForm/index.tsx
Labels: Ship It :shipit:

#1871 fix(Flyout): change how we're setting full height
  packages/gamut-labs/src/Flyout/index.tsx
Labels: Ship It :shipit:

#1875 feat(GlobalHeader): Added the better type for the link handler
  packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
Labels: Ship It :shipit:

#1877 feat(LayoutMenu): add breakpoint prop for configurable layout switching
  packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
Labels: Ship It :shipit:

#1818 feat(GridForm): Add optional sections to GridForm
  packages/gamut/src/GridForm/GridFormSections/GridFormContent.tsx
  packages/gamut/src/GridForm/GridFormSections/GridFormSection.tsx.tsx
  packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
  packages/gamut/src/GridForm/GridFormSections/GridFormSectionTitle.tsx
  packages/gamut/src/GridForm/GridFormSections/__fixtures__/renderers.tsx
  packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormContent-test.tsx
  packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormSection-test.tsx
  packages/gamut/src/GridForm/GridFormSections/__tests__/GridFormSectionTitle-test.tsx
  packages/gamut/src/GridForm/GridFormSections/index.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1821 feat: add search to GlobalHeader
  packages/gamut-labs/src/AppHeader/Search/SearchPane.tsx
  packages/gamut-labs/src/AppHeader/Search/SearchPaneContents.tsx
  packages/gamut-labs/src/AppHeader/Search/__tests__/SearchPane-test.tsx
  packages/gamut-labs/src/AppHeader/Search/__tests__/SearchPaneContents-test.tsx
  packages/gamut-labs/src/AppHeader/Search/useHeaderSearch.tsx
  packages/gamut-labs/src/AppHeader/__tests__/AppHeader-test.tsx
  packages/gamut-labs/src/AppHeader/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/MobileSearchBar.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/MobileSearchBar-test.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/__tests__/AppHeaderMobile-test.tsx
  packages/gamut-labs/src/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
  packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage-test.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/AppHeader/AppHeader.stories.mdx
  packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx
  packages/styleguide/stories/Organisms/GlobalPage.stories.mdx
Labels: Ship It :shipit:

#1874 docs(text): add some utility examples
  packages/gamut/src/Typography/variants.ts
  packages/styleguide/stories/Typography/Text.stories.mdx
Labels: Ship It :shipit:

#1881 feat: add user impression to tracking
  packages/tracking/src/events/track.ts
  packages/tracking/src/events/types.ts
Labels: Ship It :shipit:

#1882 fix: support navigator.sendBeacon not existing
  packages/tracking/src/events/__tests__/track.spec.ts
  packages/tracking/src/events/__tests__/track.test.ts
  packages/tracking/src/events/__tests__/user.spec.ts
  packages/tracking/src/events/track.ts
Labels: Auto Update, Ship It :shipit:
