Repository Codecademy/gamut, pull requests merged in 2021-09, with the labels that each got.

#2013 fix: Hiding checkbox svg from accessibility api
  packages/gamut/src/Form/Checkbox.tsx
Labels: Ship It :shipit:

#2003 feat: Adding option to set GridForm breakType to "none"
  packages/gamut/src/GridForm/GridForm.tsx
  packages/gamut/src/GridForm/GridFormSections/GridFormSectionBreak.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#2016 fix(Checkbox): safari and ff labelling
  packages/gamut/src/Form/Checkbox.tsx
  packages/styleguide/stories/Atoms/FormInputs/Checkbox.stories.mdx
Labels: Ship It :shipit:

#2015 feat(Avatar): add size prop
  packages/gamut-labs/src/Avatar/__tests__/avatar-test.tsx
  packages/gamut-labs/src/Avatar/index.tsx
Labels: Ship It :shipit:

#2021 fix(Checkbox): Safari + Firefox accessibility but better this time
  packages/gamut/src/Form/Checkbox.tsx
  packages/styleguide/stories/Atoms/FormInputs/examples.tsx
Labels: Ship It :shipit:

#2019 feat(Card)!: Add color mode to card
  packages/gamut/src/Card/index.tsx
  packages/styleguide/stories/Atoms/Card.stories.mdx
Labels: Ship It :shipit:

#2018 fix(Testimonial): mobile sizing bug fix
  packages/gamut-labs/src/Testimonial/index.tsx
Labels: Ship It :shipit:

#1998 feat: GridForm disableFieldsOnSubmit
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Form/FormWrapper.tsx
  packages/gamut/src/GridForm/GridForm.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/GridFormSections/GridFormContent.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/types.ts
  packages/gamut/src/GridForm/utils.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#2022 refactor(header): remove cc-docs from header and footer
  packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
  packages/gamut-labs/src/lib/resourcesList/index.ts
Labels: Ship It :shipit:

#2024 fix: add docs back to header and footer
  packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
  packages/gamut-labs/src/lib/resourcesList/index.ts
Labels: Ship It :shipit:

#2025 fix: Revert "fix: add docs back to header and footer"
  packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
  packages/gamut-labs/src/lib/resourcesList/index.ts
Labels: Ship It :shipit:

#2034 fix(GridForm): custom errors
  packages/gamut/src/GridForm/GridFormInputGroup/__tests__/GridFormInputGroup-test.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
Labels: Ship It :shipit:

#2026 fix: Set `Card` non variant text color to ensure no inheritance GM-347
  packages/gamut/src/Card/index.tsx
Labels: Ship It :shipit:

#2023 fix(GlobalHeader): Limit buttons on mobile header < XS to 1 and use small size GM-345
  packages/gamut-labs/src/AppHeader/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/index.tsx
Labels: Ship It :shipit:

#2033 refactor(EditorialQuote): removed editorial quote
  packages/gamut-labs/src/EditorialQuote/index.tsx
  packages/gamut-labs/src/EditorialQuote/styles.module.scss
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Brand/Molecules/EditorialQuote.stories.mdx
Labels: Ship It :shipit:

#1880 feat: add notifications to GlobalHeader
  packages/gamut-labs/src/AppHeader/Search/SearchPane.tsx
  packages/gamut-labs/src/AppHeader/Search/SearchPaneContents.tsx
  packages/gamut-labs/src/AppHeader/Search/__tests__/SearchPane-test.tsx
  packages/gamut-labs/src/AppHeader/Search/__tests__/SearchPaneContents-test.tsx
  packages/gamut-labs/src/AppHeader/Search/useHeaderSearch.tsx
  packages/gamut-labs/src/AppHeader/index.tsx
  packages/gamut-labs/src/AppHeader/shared.tsx
  packages/gamut-labs/src/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
  packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage-test.tsx
  packages/gamut-labs/src/HeaderHeightArea/index.tsx
  packages/gamut-labs/src/HeaderHeightArea/useIsInHeaderRegion.ts
  packages/gamut-labs/src/Notifications/NotificationBell.tsx
  packages/gamut-labs/src/Notifications/NotificationsContents.tsx
  packages/gamut-labs/src/Notifications/NotificationsPopover.tsx
  packages/gamut-labs/src/Notifications/__fixtures__/stubs.ts
  packages/gamut-labs/src/Notifications/__tests__/NotificationBell-test.tsx
  packages/gamut-labs/src/Notifications/__tests__/NotificationsContents-test.tsx
  packages/gamut-labs/src/Notifications/__tests__/useHeaderNotifications-test.tsx
  packages/gamut-labs/src/Notifications/__tests__/useNotificationButtons-test.tsx
  packages/gamut-labs/src/Notifications/types.ts
  packages/gamut-labs/src/Notifications/useHeaderNotifications.tsx
  packages/gamut-labs/src/Notifications/useNotificationButtons.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut-tests/src/index.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Organisms/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#2042 fix: Revert "fix: Revert "fix: add docs back to header and footer""
  packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
  packages/gamut-labs/src/lib/resourcesList/index.ts
Labels: Ship It :shipit:

#2043 fix(GlobalHeader): corrected 360px for notifications
  packages/gamut-labs/src/Notifications/NotificationsContents.tsx
  packages/gamut-labs/src/Notifications/NotificationsPopover.tsx
Labels: Ship It :shipit:

#2037 docs: Relinked Figma link for Tooltips
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#2045 fix(GridFormCheckbox): tight variant error spacing
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#2036 fix(babel-preset-codecademy): remove loose option
  packages/babel-preset-codecademy/index.js
Labels: Ship It :shipit:, Auto Update

#2046 fix(Testimonial): pass display prop to Anchor if href is defined
  packages/gamut-labs/src/Testimonial/__tests__/Testimonial-test.tsx
  packages/gamut-labs/src/Testimonial/index.tsx
Labels: Ship It :shipit:

#2050 chore(styleguide): remove 'storybook' prefix from deploy URIs
  .circleci/config.yml
Labels: Ship It :shipit:

#2030 chore: use Jest projects internally
  jest.config.base.js
  jest.config.js
  packages/gamut-icons/jest.config.js
  packages/gamut-illustrations/jest.config.js
  packages/gamut-kit/jest.config.js
  packages/gamut-labs/jest.config.js
  packages/gamut-patterns/jest.config.js
  packages/gamut-styles/jest.config.js
  packages/gamut-system/jest.config.js
  packages/gamut-tests/jest.config.js
  packages/gamut/jest.config.js
  packages/konamimojisplosion/jest.config.js
  packages/macros/jest.config.js
  packages/markdown-overrides/jest.config.js
  packages/monaco/jest.config.js
  packages/styleguide/jest.config.js
  packages/tracking/jest.config.js
  packages/variance/jest.config.js
  script/jest/rtl-setup.js
  script/jest/rtl-setup.ts
Labels: Ship It :shipit:

#2044 feat(Styleguide): use green background for localhost storybook
  packages/styleguide/.storybook/theme.ts
Labels: Ship It :shipit:

#2014 feat(List): Adds List presentation components GM-185
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/List/List.tsx
  packages/gamut/src/List/ListCol.tsx
  packages/gamut/src/List/ListProvider.tsx
  packages/gamut/src/List/ListRow.tsx
  packages/gamut/src/List/__tests__/List-test.tsx
  packages/gamut/src/List/elements.tsx
  packages/gamut/src/List/index.tsx
  packages/gamut/src/List/types.ts
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/stories/Molecules/List/examples.tsx
  packages/styleguide/stories/Molecules/List/index.stories.mdx
Labels: Ship It :shipit:, Next Release

#2048 fix: Set HubCard Card variant
  packages/gamut-labs/src/HubCard/index.tsx
Labels: Ship It :shipit:, Next Release

#2049 fix(Markdown): use empty content for li::before
  packages/gamut/src/Markdown/styles/_mixins.scss
Labels: Ship It :shipit:

#2052 docs: less green on localhost
  packages/styleguide/.storybook/components/Docs/DocsPage.tsx
  packages/styleguide/.storybook/theme.ts
Labels: Ship It :shipit:

#2012 feat(GridForm): resetOnSubmit
  packages/gamut/src/Form/FormWrapper.tsx
  packages/gamut/src/Form/SubmitButton.tsx
  packages/gamut/src/GridForm/GridForm.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/GridForm/utils.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
  packages/styleguide/stories/Organisms/examples.tsx
Labels: Ship It :shipit:, Next Release

#2053 feat(Avatar)!: convert avatar sizes to using numbers over string enum
  packages/gamut-labs/src/Avatar/__tests__/avatar-test.tsx
  packages/gamut-labs/src/Avatar/index.tsx
Labels: Ship It :shipit:

#2058 fix(Illustrations): add titles to illustrations
  packages/gamut-illustrations/src/Bee.tsx
  packages/gamut-illustrations/src/Browser.tsx
  packages/gamut-illustrations/src/BrowserLock.tsx
  packages/gamut-illustrations/src/BrowserPuzzle.tsx
  packages/gamut-illustrations/src/Confetti.tsx
  packages/gamut-illustrations/src/EmailAt.tsx
  packages/gamut-illustrations/src/Hills.tsx
  packages/gamut-illustrations/src/HomeOffice.tsx
  packages/gamut-illustrations/src/NumberBlocks.tsx
  packages/gamut-illustrations/src/Plant.tsx
  packages/gamut-illustrations/src/Python.tsx
  packages/gamut-illustrations/src/Sun.tsx
  packages/gamut-illustrations/src/Target.tsx
Labels: Ship It :shipit:

#2062 chore: remove storybook from url
  .circleci/config.yml
  .gitignore
  dist/static/robots.txt
  dist/static/storybook/index.html
  package.json
  packages/styleguide/package.json
Labels: Ship It :shipit:

#2057 fix(NotificationList): a11y improvements
  packages/gamut-labs/src/Notifications/NotificationBell.tsx
  packages/gamut-labs/src/Notifications/NotificationsContents.tsx
  packages/gamut-labs/src/Notifications/types.ts
  packages/gamut-labs/src/Notifications/useNotificationButtons.tsx
  packages/gamut/src/NotificationList/EmptyNotification/index.tsx
  packages/gamut/src/NotificationList/index.tsx
Labels: Ship It :shipit:

#2059 fix(Testimonial): aria-label on Anchor
  packages/gamut-labs/src/Testimonial/index.tsx
Labels: Ship It :shipit:

#1976 feat(GlobalHeader, GlobalFooter): Learner stories link in global footer and global header
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
Labels: Ship It :shipit:, Auto Update

#2038 feat(modal): scrollable prop to Modal
  packages/gamut/src/Modals/Modal.tsx
  packages/styleguide/stories/Molecules/Modals/Modal.stories.mdx
Labels: Ship It :shipit:

#2040 feat(icon): Megaphone Icon
  packages/gamut-icons/src/svg/regular/megaphone-icon.svg
Labels: Ship It :shipit:

#2071 feat(icons): full suite of mini-arrows
  packages/gamut-icons/src/svg/mini/mini-arrow-left-icon.svg
  packages/gamut-icons/src/svg/mini/mini-arrow-up-icon.svg
Labels: Ship It :shipit:

#2010 docs: Relinked and cleaned up Figma Links
  packages/styleguide/stories/Atoms/Card.stories.mdx
  packages/styleguide/stories/Atoms/Pattern.stories.mdx
  packages/styleguide/stories/Atoms/Patterns.stories.mdx
  packages/styleguide/stories/Brand/Atoms/Avatar.stories.mdx
Labels: Ship It :shipit:

#2063 feat(LayoutMenu): additional links section above accordions
  packages/gamut-labs/src/LayoutMenu/AccordionMenu.tsx
  packages/gamut-labs/src/LayoutMenu/LayoutMenu.tsx
  packages/gamut-labs/src/LayoutMenu/LayoutMenuSection.tsx
  packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenu-test.tsx
  packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenuSection-test.tsx
  packages/styleguide/stories/Organisms/LayoutMenu.stories.mdx
Labels: Ship It :shipit:

#2001 feat(icon): StarCircleIcon
  packages/gamut-icons/src/svg/regular/star-circle-icon.svg
Labels: Ship It :shipit:

#2067 feat(CurriculumCard)!: Updated scope to support more content items, added alternative subtitle
  packages/gamut-labs/src/CurriculumCard/Subtitle/__tests__/Subtitle-test.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/helpers.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
  packages/gamut-labs/src/CurriculumCard/__tests__/CurriculumCard-test.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/styleguide/stories/Molecules/CurriculumCard.stories.mdx
Labels: Ship It :shipit:, Next Release

#2068 fix(SelectDropdown): parse options fix for select dropdown
  packages/gamut/src/Form/__tests__/SelectDropdown-test.tsx
  packages/gamut/src/Form/__tests__/__snapshots__/utils-test.tsx.snap
  packages/gamut/src/Form/__tests__/utils-test.tsx
  packages/gamut/src/Form/utils.tsx
  packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
  packages/styleguide/stories/Atoms/FormInputs/SelectDropdown.stories.mdx
Labels: Ship It :shipit:

#2064 feat(docs): elaborate Popover vs ToolTip
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
  packages/styleguide/stories/Molecules/Popover/index.stories.mdx
Labels: Ship It :shipit:, Auto Update

#2072 feat(PageHero): add optional eyebrow text
  packages/gamut-labs/src/LandingPage/PageHero.tsx
  packages/gamut-labs/src/LandingPage/__tests__/Hero-test.tsx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
Labels: Ship It :shipit:

#2065 refactor(LayoutMenu): text wrapping support for section items and link
  packages/gamut-labs/src/LayoutMenu/SectionItemLink.tsx
Labels: Ship It :shipit:

#2075 feat: update landing page `CTA` to show fill button or cta button
  packages/gamut-labs/src/LandingPage/CTA.tsx
  packages/gamut-labs/src/LandingPage/PageFeatures.tsx
  packages/gamut-labs/src/LandingPage/PageHero.tsx
  packages/gamut-labs/src/LandingPage/PagePrefooter.tsx
  packages/gamut-labs/src/LandingPage/PageVideoGallery.tsx
  packages/gamut-labs/src/LandingPage/types.tsx
  packages/styleguide/stories/Brand/Organisms/PageFeatures.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PagePrefooter.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageVideoGallery.stories.mdx
Labels: Ship It :shipit:

#2078 chore: Remove storyshots for some CI Savings GM-377
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/.storybook/main.ts
  packages/styleguide/__tests__/runSplitStoryshotsTests.ts
  packages/styleguide/__tests__/storyshots/storybook-0-test.ts
  packages/styleguide/__tests__/storyshots/storybook-1-test.ts
  packages/styleguide/__tests__/storyshots/storybook-2-test.ts
  packages/styleguide/__tests__/storyshots/storybook-3-test.ts
  packages/styleguide/__tests__/storyshots/storybook-4-test.ts
  packages/styleguide/__tests__/storyshots/storybook-5-test.ts
  packages/styleguide/__tests__/storyshots/storybook-6-test.ts
  packages/styleguide/__tests__/storyshots/storybook-7-test.ts
  packages/styleguide/__tests__/storyshots/storybook-8-test.ts
  packages/styleguide/package.json
  yarn.lock
Labels: Ship It :shipit:

#2076 feat(CurriculumCard): updated footer text variant
  packages/gamut-labs/src/CurriculumCard/Footer/__tests__/Footer-test.tsx
  packages/gamut-labs/src/CurriculumCard/Footer/index.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/styleguide/stories/Molecules/CurriculumCard.stories.mdx
Labels: Ship It :shipit:

#2074 feat(Tooltip): introduced widthMode
  packages/gamut/src/ToolTip/index.tsx
Labels: Ship It :shipit:

#2077 feat(PageHero)!: add short text variation
  packages/gamut-labs/src/LandingPage/PageHero.tsx
  packages/gamut-labs/src/LandingPage/PageHeroMedia.tsx
  packages/gamut-labs/src/LandingPage/__tests__/Hero-test.tsx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
Labels: Ship It :shipit:

#2085 feat(PageHero): add option to show image on mobile
  packages/gamut-labs/src/LandingPage/PageHero.tsx
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
Labels: Ship It :shipit:, Auto Update

#2061 fix(GridForm): Add keyboard focus on form tooltips
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/gamut/src/ToolTip/index.tsx
  packages/styleguide/stories/Atoms/FormInputs/Radio.stories.mdx
Labels: Ship It :shipit:

#2083 feat(Drawer): extract Drawer from Flyout
  packages/gamut-labs/src/Drawer/__tests__/Drawer-test.tsx
  packages/gamut-labs/src/Drawer/index.tsx
  packages/gamut-labs/src/Flyout/__tests__/Flyout-test.tsx
  packages/gamut-labs/src/Flyout/index.tsx
  packages/gamut-labs/src/LayoutMenu/__tests__/LayoutMenu-test.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut-styles/src/variables/timing.ts
  packages/gamut/src/Form/styles/Radio-styles.ts
  packages/styleguide/stories/Atoms/Drawer.stories.mdx
  packages/styleguide/stories/Molecules/Flyout.stories.mdx
  packages/styleguide/stories/Molecules/Flyout/FlyoutExample.tsx
  packages/styleguide/stories/Molecules/Flyout/index.stories.mdx
Labels: Ship It :shipit:
