Repository Codecademy/gamut, pull requests merged in 2021-04, with the labels that each got.

#1567 feat(GridForm): Update the buttons for GridForm submit
  packages/gamut/src/GridForm/GridFormSubmit/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Ship It :shipit:

#1558 feat(Input): React-Recurly edits
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Form/Input.tsx
  packages/gamut/src/Form/styles/shared.tsx
  packages/styleguide/stories/Atoms/FormInputs/Input.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1600 fix: Typo...
  packages/styleguide/.storybook/components/Docs/DocsPage.tsx
Labels: Ship It :shipit:

#1599 feat(Docs): Docs refresh (Grid, Legacy Colors, Typography) [GM-118] [GM-194]
  packages/styleguide/.storybook/components/Scales/Scale.tsx
  packages/styleguide/.storybook/components/Scales/Swatches.tsx
  packages/styleguide/.storybook/components/Scales/TextExample.tsx
  packages/styleguide/.storybook/components/index.tsx
  packages/styleguide/stories/Foundations/Colors/constants.tsx
  packages/styleguide/stories/Foundations/Colors/index.stories.mdx
  packages/styleguide/stories/Foundations/Colors/tables.tsx
  packages/styleguide/stories/Foundations/Layout.stories.mdx
  packages/styleguide/stories/Foundations/Theme/index.stories.mdx
  packages/styleguide/stories/Foundations/Typography.stories.mdx
Labels: Ship It :shipit:

#1580 feat(Variance): Initial Props and Refactor Tests [WEB-1390]
  packages/gamut-kit/package.json
  packages/gamut-labs/package.json
  packages/gamut-styles/package.json
  packages/gamut-styles/src/variance/config.ts
  packages/gamut-styles/src/variance/props.ts
  packages/gamut-styles/src/variance/utils.ts
  packages/gamut/package.json
  packages/variance/.npmignore
  packages/variance/README.md
  packages/variance/__tests__/component-test.tsx
  packages/variance/__tests__/variance-test.ts
  packages/variance/package.json
  packages/variance/src/core.ts
  packages/variance/src/index.ts
  packages/variance/src/transforms/__tests__/transformSize-test.ts
  packages/variance/src/transforms/index.ts
  packages/variance/src/transforms/transformSize.ts
  packages/variance/src/tsconfig.json
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
  packages/variance/src/types/props.ts
  packages/variance/tsconfig.base.json
  packages/variance/tsconfig.json
Labels: Ship It :shipit:

#1601 fix: allow empty strings for anchor and button hrefs
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/__tests__/ButtonOutline-test.tsx
Labels: Ship It :shipit:

#1604 fix(ToolTip): A11y Update
  packages/gamut/src/ToolTip/index.tsx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#1605 fix(ToolTip): Revert A11y Update
  packages/gamut/src/ToolTip/index.tsx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#1545 feat(ColorModes): Base ColorMode support and serialization of color variables [GM-177]
  package.json
  packages/gamut-styles/package.json
  packages/gamut-styles/src/AssetProvider.tsx
  packages/gamut-styles/src/Background.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/GamutProvider.tsx
  packages/gamut-styles/src/__tests__/Background-test.tsx
  packages/gamut-styles/src/index.ts
  packages/gamut-styles/src/theme.ts
  packages/gamut-styles/src/utilities/createThemeVariables.ts
  packages/gamut-styles/src/utilities/createVariables.ts
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut-system/package.json
  packages/gamut/package.json
  packages/styleguide/.storybook/components/Docs/DocsContainer.tsx
  packages/styleguide/.storybook/components/utils.ts
  packages/styleguide/.storybook/decorators/theme.tsx
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/.storybook/theme.ts
  packages/styleguide/package.json
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/ColorMode/index.stories.mdx
  packages/styleguide/stories/Foundations/Theme/index.stories.mdx
  packages/styleguide/stories/Foundations/Theme/tables.tsx
  packages/styleguide/stories/Layouts/Elements/index.tsx
  packages/styleguide/stories/Typography/Anchor.stories.mdx
  packages/variance/package.json
  yarn.lock
Labels: Next Release, Ship It :shipit:

#1606 fix(ToolTip): A11y Updates (revert of revert)
  packages/gamut/src/ToolTip/index.tsx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
Labels: Ship It :shipit:

#1562 docs: added Contributing blurb for a new package
  packages/styleguide/stories/Meta/Contributing.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1588 docs: reference Dialog in old Modal story
  packages/styleguide/stories/Molecules/Modal.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1609 chore: removed Intellimize IDs
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/styleguide/stories/Molecules/Modal.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1612 fix(Variance): Add better prop sorting tests
  packages/variance/integration/__fixtures__/theme.ts
  packages/variance/integration/__tests__/component-test.tsx
  packages/variance/integration/__tests__/variance-test.ts
  packages/variance/integration/index.ts
  packages/variance/integration/tsconfig.json
  packages/variance/src/utils/__fixtures__/testConfig.ts
  packages/variance/src/utils/__tests__/propNames-test.ts
  packages/variance/src/utils/propNames.ts
  packages/variance/tsconfig.json
Labels: Ship It :shipit:

#1613 chore(labs): Add watch task to labs
  packages/gamut-labs/package.json
Labels: Auto Update, Ship It :shipit:

#1615 chore: Better Deprecation Warnings GM-198
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut-styles/src/variables/deprecated-colors.ts
  packages/gamut/src/Accordion/index.tsx
  packages/gamut/src/AccordionArea/index.tsx
  packages/gamut/src/AccordionButton/index.tsx
  packages/gamut/src/ButtonDeprecated/index.tsx
  packages/gamut/src/ButtonDeprecatedBase/index.tsx
  packages/gamut/src/DeprecatedCard/CardBody.tsx
  packages/gamut/src/DeprecatedCard/CardContent/index.tsx
  packages/gamut/src/DeprecatedCard/CardEyebrow/index.tsx
  packages/gamut/src/DeprecatedCard/CardFooter.tsx
  packages/gamut/src/DeprecatedCard/CardHeader/index.tsx
  packages/gamut/src/DeprecatedCard/CardShell.tsx
  packages/gamut/src/DeprecatedCard/CardStack/index.tsx
  packages/gamut/src/FlexBox/Container.tsx
  packages/gamut/src/FlexBox/Item.tsx
  packages/gamut/src/FlexGrid/Col.tsx
  packages/gamut/src/FlexGrid/FlexGrid.tsx
  packages/gamut/src/FlexGrid/Row.tsx
  packages/gamut/src/HighlightedText/index.tsx
  packages/gamut/src/Menus/MenuItem/index.tsx
  packages/gamut/src/Menus/SideMenu/index.tsx
  packages/gamut/src/Modal/index.tsx
  packages/gamut/src/NotificationList/NotificationIcon.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/NotificationList/index.tsx
  packages/gamut/src/RadialProgress/index.tsx
  packages/gamut/src/SplitInterstitial/index.tsx
  packages/gamut/src/Tabs/Tab/index.tsx
  packages/gamut/src/Tabs/TabList/index.tsx
  packages/gamut/src/Tabs/TabPanel/index.tsx
  packages/gamut/src/Tabs/Tabs/index.tsx
  packages/gamut/src/Typography/HeadingDeprecated.tsx
  packages/gamut/src/Typography/TextDeprecated.tsx
  packages/gamut/src/deprecated/Icon/iconMap.tsx
  packages/gamut/src/deprecated/Icon/index.tsx
Labels: Ship It :shipit:

#1572 fix: Adding a11y fixes to NotificationListNew
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/NotificationListNew/index.tsx
Labels: Ship It :shipit:

#1597 refactor(SplitInterstitial): deleting split interstitial
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/SplitInterstitial/__tests__/SplitInterstitial-test.tsx
  packages/gamut/src/SplitInterstitial/assets/blueCurve.svg
  packages/gamut/src/SplitInterstitial/assets/purpleCurveBottomRight.svg
  packages/gamut/src/SplitInterstitial/assets/purpleCurveTopLeft.svg
  packages/gamut/src/SplitInterstitial/index.tsx
  packages/gamut/src/SplitInterstitial/styles.module.scss
  packages/gamut/src/index.tsx
Labels: Ship It :shipit:

#1620 fix: accessibility and key violations in GlobalFooter
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/SocialMediaLinks.tsx
Labels: Auto Update, Ship It :shipit:

#1622 feat(Icons): Add MiniArrowRightIcon
  packages/gamut-icons/src/svg/mini/mini-arrow-right-icon.svg
Labels: Ship It :shipit:

#1610 fix: added component-test-setup to gamut-kit
  packages/gamut-kit/package.json
  packages/gamut-tests/package.json
  packages/gamut/src/AccordionArea/__tests__/AccordionArea-test.tsx
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1625 fix: use internal App Store and Google Play images
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/assets/download-on-the-app-store.svg
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/assets/get-it-on-google-play.png
  typings/png.d.ts
Labels: Auto Update, Ship It :shipit:

#1629 fix: corrected GlobalFooter shop link
  packages/gamut-labs/src/experimental/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Auto Update, Ship It :shipit:

#1623 feat(NotificationList)!: Replaced old NotificationList & NotificationListItem w/ upgraded components
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/NotificationList/EmptyNotification/emptyNotificationContents.tsx
  packages/gamut/src/NotificationList/EmptyNotification/index.tsx
  packages/gamut/src/NotificationList/NotificationIcon.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationIcon-test.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationItem-test.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationItemNew-test.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationList-test.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationListNew-test.tsx
  packages/gamut/src/NotificationList/index.tsx
  packages/gamut/src/NotificationList/styles/Notification.module.scss
  packages/gamut/src/NotificationList/styles/NotificationIcon.module.scss
  packages/gamut/src/NotificationList/styles/index.module.scss
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/NotificationListNew/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1611 feat(ThemeBuilder): TypeSafe theme construction + variable serialization [WEB-1401]
  packages/gamut-styles/src/Background.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/GamutProvider.tsx
  packages/gamut-styles/src/__tests__/Background-test.tsx
  packages/gamut-styles/src/theme.ts
  packages/gamut-styles/src/utilities/createThemeVariables.ts
  packages/gamut-styles/src/utilities/createVariables.ts
  packages/gamut-styles/src/utilities/index.ts
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut-styles/src/variance/config.ts
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/ColorMode/index.stories.mdx
  packages/styleguide/stories/Foundations/Theme/tables.tsx
  packages/variance/integration/__fixtures__/theme.ts
  packages/variance/integration/index.ts
  packages/variance/src/createTheme/createTheme.test.ts
  packages/variance/src/createTheme/createTheme.ts
  packages/variance/src/createTheme/index.ts
  packages/variance/src/createTheme/serializeTokens.ts
  packages/variance/src/index.ts
  packages/variance/src/types/theme.ts
Labels: Ship It :shipit:

#1449 feat(LayoutGrid): LayoutGrid conversion + Initial Variance Props [GM-81]
  packages/gamut-labs/src/landingPage/PageFeatures.tsx
  packages/gamut-labs/src/landingPage/PageHero.tsx
  packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
  packages/gamut-styles/src/index.ts
  packages/gamut-styles/src/variance/index.ts
  packages/gamut-styles/src/variance/utils.ts
  packages/gamut/src/GridForm/GridFormSubmit/index.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/gamut/src/Layout/Column.tsx
  packages/gamut/src/Layout/LayoutGrid.tsx
  packages/gamut/src/Layout/index.tsx
  packages/gamut/src/Layout/styles/Column.module.scss
  packages/gamut/src/Layout/styles/Grid.module.scss
  packages/gamut/src/Layout/styles/_variables.scss
  packages/gamut/src/Layout/types.ts
  packages/gamut/src/Typography/HeadingDeprecated.tsx
  packages/gamut/src/Typography/TextDeprecated.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Foundations/Layout.stories.mdx
  packages/styleguide/stories/Layouts/Elements/index.tsx
  packages/styleguide/stories/Layouts/FlexContainer.stories.mdx
  packages/styleguide/stories/Layouts/FlexGrid.stories.mdx
  packages/styleguide/stories/Layouts/LayoutGrid.stories.mdx
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
  packages/variance/integration/__tests__/variance-test.ts
  packages/variance/src/core.ts
  packages/variance/src/types/props.ts
  packages/variance/src/types/theme.ts
  packages/variance/src/utils/responsive.ts
Labels: Ship It :shipit:

#1626 fix: adding aria-required for required GridForm fields
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
Labels: Ship It :shipit:

#1627 feat(Icons): Add GraphStatsAscendIcon
  packages/gamut-icons/src/svg/regular/graph-stats-ascend-icon.svg
Labels: Ship It :shipit:

#1642 fix(labs): Fix missing exported type
  packages/gamut-labs/src/index.ts
Labels: Ship It :shipit:

#1621 feat(Icons): Add checkout icons
  packages/gamut-icons/src/svg/regular/conversation-chat-icon.svg
  packages/gamut-icons/src/svg/regular/file-lock-icon.svg
  packages/gamut-icons/src/svg/regular/map-finger-icon.svg
  packages/gamut-icons/src/svg/regular/map-pin-icon.svg
  packages/gamut-icons/src/svg/regular/programming-browser-icon.svg
Labels: Ship It :shipit:

#1643 feat: added new Target illustration
  packages/gamut-illustrations/src/Target.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Ship It :shipit:

#1647 fix(Props): Adds alignment props to both grid and flex
  packages/gamut-styles/src/variance/config.ts
Labels: Ship It :shipit:

#1644 chore(ContentContainer): Convert ContentContainer to variance API [GM-206]
  packages/gamut/src/ContentContainer/index.tsx
Labels: Ship It :shipit:

#1635 chore(Card): Migrate to Variance and more performant structure.
  packages/gamut-labs/src/HubCard/index.tsx
  packages/gamut-styles/src/variance/config.ts
  packages/gamut/src/Card/index.tsx
  packages/styleguide/.storybook/components/Navigation/TableOfContents.tsx
  packages/styleguide/stories/Atoms/Card.stories.mdx
  packages/styleguide/stories/Brand/Atoms/HubCard.stories.mdx
Labels: Next Release, Ship It :shipit:

#1608 feat(SelectDropdown): Select with styled dropdown
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/package.json
  packages/gamut/src/Form/Select.tsx
  packages/gamut/src/Form/SelectDropdown.tsx
  packages/gamut/src/Form/__tests__/SelectDropdown-test.tsx
  packages/gamut/src/Form/index.tsx
  packages/gamut/src/Form/styles/shared.tsx
  packages/styleguide/stories/Atoms/FormInputs/Select.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1650 feat!: add new dot Pattern and rename old dots to checker
  packages/gamut-labs/src/Popover/__tests__/Popover-test.tsx
  packages/gamut/src/Dialog/index.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/Pattern/defs.tsx
  packages/gamut/src/Pattern/index.tsx
  packages/styleguide/stories/Atoms/Pattern.stories.mdx
  packages/styleguide/stories/Molecules/Coachmark/index.stories.mdx
  packages/styleguide/stories/Molecules/Popover/Popover.examples.tsx
Labels: Ship It :shipit:

#1639 feat(Curriculum Card): Port from monolith
  packages/gamut-labs/src/CurriculumCard/BottomTag/__tests__/BottomTag-test.tsx
  packages/gamut-labs/src/CurriculumCard/BottomTag/index.tsx
  packages/gamut-labs/src/CurriculumCard/Difficulty/__tests__/Difficulty-test.tsx
  packages/gamut-labs/src/CurriculumCard/Difficulty/index.tsx
  packages/gamut-labs/src/CurriculumCard/Footer/__tests__/Footer-test.tsx
  packages/gamut-labs/src/CurriculumCard/Footer/index.tsx
  packages/gamut-labs/src/CurriculumCard/Header/__tests__/Header-test.tsx
  packages/gamut-labs/src/CurriculumCard/Header/index.tsx
  packages/gamut-labs/src/CurriculumCard/Image/__tests__/Image-test.tsx
  packages/gamut-labs/src/CurriculumCard/Image/index.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/__tests__/Subtitle-test.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
  packages/gamut-labs/src/CurriculumCard/__tests__/CurriculumCard-test.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut-labs/src/remoteAssets/components.ts
  packages/styleguide/stories/Molecules/CurriculumCard.stories.mdx
Labels: Ship It :shipit:

#1653 refactor: add additional properties to userclickdata
  packages/tracking/src/types.ts
Labels: Ship It :shipit:

#1632 feat: Add PageSection molecule
  packages/gamut-labs/src/PageSection/__tests__/PageSection-test.tsx
  packages/gamut-labs/src/PageSection/index.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut/src/Button/TextButton.tsx
  packages/styleguide/stories/Molecules/PageSection.stories.mdx
Labels: Ship It :shipit:

#1660 chore: Turn off constructed stylesheets in dev
  packages/gamut-styles/src/cache/index.ts
Labels: Ship It :shipit:

#1663 fix: stop providing flat to ButtonDeprecatedBase in AccordionButton
  packages/gamut/src/AccordionButton/index.tsx
Labels: Auto Update, Ship It :shipit:

#1666 fix: Add GamutProvider Tests and Remove .storybook from coverage
  jest.config.js
  packages/gamut-styles/src/GamutProvider.tsx
  packages/gamut-styles/src/__tests__/Background-test.tsx
  packages/gamut-styles/src/__tests__/GamutProvider-test.tsx
  packages/gamut-styles/src/cache/__tests__/createEmotionCache-test.ts
  packages/gamut-styles/src/cache/createEmotionCache.ts
  packages/gamut-styles/src/cache/index.ts
  packages/gamut-styles/src/globals/Variables.tsx
Labels: Ship It :shipit:

#1641 docs: Add Dynamic tables for System Props + Compose Docs [WEB-1414]
  packages/styleguide/stories/Foundations/System/Compose.stories.mdx
  packages/styleguide/stories/Foundations/System/Props.stories.mdx
  packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
  packages/styleguide/stories/Foundations/System/tables.tsx
Labels: Ship It :shipit:

#1665 fix(GlobalFooter): update empty global footer onClick targets
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CatalogLinks.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Ship It :shipit:

#1668 fix: cache constants missing
  packages/gamut-styles/src/cache/index.ts
Labels: Ship It :shipit:

#1655 feat(Text): Migrate to variance and add new semantic variants [GM-204]
  packages/gamut-labs/src/CurriculumCard/BottomTag/index.tsx
  packages/gamut-labs/src/CurriculumCard/Difficulty/index.tsx
  packages/gamut-labs/src/CurriculumCard/Footer/index.tsx
  packages/gamut-labs/src/CurriculumCard/Header/index.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/__tests__/Subtitle-test.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/gamut-labs/src/GlobalFooter/FooterHeading.tsx
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/GlobalFooter/FooterSubHeading.tsx
  packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter-test.tsx
  packages/gamut-labs/src/landingPage/PageVideoGallery.tsx
  packages/gamut-labs/src/landingPage/Title.tsx
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/Typography/Text.tsx
  packages/gamut/src/Typography/index.ts
  packages/gamut/src/Typography/variants.ts
  packages/gamut/src/index.tsx
  packages/styleguide/.storybook/components/Docs/DocsPage.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/Typography.stories.mdx
  packages/styleguide/stories/Typography/Text.stories.mdx
Labels: Next Release, Ship It :shipit:

#1661 fix(Column): Make Columns statically 12 on the base
  packages/gamut/src/Layout/Column.tsx
  packages/gamut/src/Layout/LayoutGrid.tsx
Labels: Next Release, Ship It :shipit:

#1619 feat(Anchor): Variance Migration + ColorMode [GM-203]
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/SocialMediaLinks.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/gamut-styles/src/index.ts
  packages/gamut/src/Anchor/index.tsx
  packages/gamut/src/BodyPortal/index.tsx
  packages/gamut/src/ButtonBase/ButtonBase.tsx
  packages/gamut/src/Modal/__tests__/Modal-test.tsx
  packages/gamut/src/Overlay/__tests__/Overlay-test.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Typography/Anchor.stories.mdx
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
Labels: Next Release, Ship It :shipit:

#1675 chore: remove codecov
  .circleci/config.yml
  codecov.yml
Labels: Ship It :shipit:

#1676 fix: Link Color
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/NotificationList/index.tsx
Labels: Ship It :shipit:

#1679 fix(Anchor): Allow inline anchors to wrap correctly
  packages/gamut/src/Anchor/index.tsx
Labels: Ship It :shipit:

#1678 fix(ColorMode): Ref Forarding for BG + ColorMode
  packages/gamut-styles/src/Background.tsx
  packages/gamut-styles/src/ColorMode.tsx
Labels: Ship It :shipit:

#1673 feat(NotificationItem): Open internal notification links in same tab
  packages/gamut/src/NotificationList/NotificationItem.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationItem-test.tsx
  packages/gamut/src/NotificationList/__tests__/NotificationList-test.tsx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
Labels: Ship It :shipit:

#1684 fix(PageSection): Adding margin-top to footer of PageSection
  packages/gamut-labs/src/PageSection/index.tsx
Labels: Ship It :shipit:

#1682 feat(Global Footer): add affiliate program link
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Ship It :shipit:

#1683 fix(Text): Fontweight for body text and none scalar typings
  packages/gamut/src/Typography/variants.ts
  packages/variance/src/types/config.ts
  packages/variance/src/types/properties.ts
Labels: Ship It :shipit:

#1680 refactor!: update landing page exports
  packages/gamut-labs/src/LandingPage/CTA.tsx
  packages/gamut-labs/src/LandingPage/Description.tsx
  packages/gamut-labs/src/LandingPage/Feature.tsx
  packages/gamut-labs/src/LandingPage/PageFeatures.tsx
  packages/gamut-labs/src/LandingPage/PageHero.tsx
  packages/gamut-labs/src/LandingPage/PageHeroMedia.tsx
  packages/gamut-labs/src/LandingPage/PagePrefooter.tsx
  packages/gamut-labs/src/LandingPage/PageVideoGallery.tsx
  packages/gamut-labs/src/LandingPage/Title.tsx
  packages/gamut-labs/src/LandingPage/__tests__/FeaturesSection-test.tsx
  packages/gamut-labs/src/LandingPage/__tests__/Hero-test.tsx
  packages/gamut-labs/src/LandingPage/__tests__/Prefooter-test.tsx
  packages/gamut-labs/src/LandingPage/__tests__/VideoGallery-test.tsx
  packages/gamut-labs/src/LandingPage/index.ts
  packages/gamut-labs/src/LandingPage/types.tsx
  packages/gamut-labs/src/LandingPage/variants.tsx
  packages/gamut-labs/src/index.ts
Labels: Ship It :shipit:

#1681 feat: List Section
  packages/gamut-labs/src/ListSection/__tests__/ListSection-test.tsx
  packages/gamut-labs/src/ListSection/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/ListSection.stories.mdx
Labels: Ship It :shipit:

#1687 chore: bump component-test-setup to 0.2.5
  package.json
  packages/gamut-kit/package.json
  packages/gamut-styles/package.json
  yarn.lock
Labels: Ship It :shipit:

#1688 fix: remove codecov badge
  README.md
Labels: Ship It :shipit:

#1685 fix(Anchor): Fixes pseudo state text decoration mismatches
  packages/gamut/src/Anchor/index.tsx
Labels: Ship It :shipit:

#1637 feat(Logo / Labels): Consolidation + Props + Modes [GM-149] [GM-146]
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderLogo/index.tsx
  packages/gamut-labs/src/CurriculumCard/Header/__tests__/Header-test.tsx
  packages/gamut-labs/src/CurriculumCard/Header/index.tsx
  packages/gamut-labs/src/CurriculumCard/Subtitle/index.tsx
  packages/gamut-labs/src/CurriculumCard/index.tsx
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Logo/Logo.tsx
  packages/gamut/src/Logo/LogoDefault.tsx
  packages/gamut/src/Logo/LogoMini.tsx
  packages/gamut/src/Logo/LogoPro.tsx
  packages/gamut/src/Logo/index.tsx
  packages/gamut/src/Logo/shared.tsx
  packages/gamut/src/ProLabel/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Atoms/Logo.stories.mdx
  packages/styleguide/stories/Atoms/ProLabel.stories.mdx
  packages/styleguide/stories/Brand/Atoms/ProLogo.stories.mdx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
Labels: Next Release, Ship It :shipit:

#1659 feat(Buttons): ColorModes + Props + Refactor + Refs Oh My! [GM-211] [REACH-856] [GM-192]
  packages/gamut-styles/src/styles/fontSmoothing.ts
  packages/gamut/src/Alert/__tests__/Alert-test.tsx
  packages/gamut/src/Banner/__tests__/Banner-test.tsx
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/CTAButton.tsx
  packages/gamut/src/Button/FillButton.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/StrokeButton.tsx
  packages/gamut/src/Button/TextButton.tsx
  packages/gamut/src/Button/__tests__/ButtonOutline-test.tsx
  packages/gamut/src/Button/index.ts
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/Button/types.ts
  packages/gamut/src/ButtonBase/ButtonBase.tsx
  packages/gamut/src/ButtonBase/__tests__/ButtonOutline-test.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/ToolTip/index.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/Utilities.stories.mdx
  packages/variance/src/createTheme/serializeTokens.ts
Labels: Next Release, Ship It :shipit:

#1674 chore(Text): Remove labs text and last uses of `TextDeprecated`.
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
  packages/gamut-labs/src/HubCard/index.tsx
  packages/gamut-labs/src/LandingPage/Feature.tsx
  packages/gamut-labs/src/Text/index.tsx
  packages/gamut-labs/src/index.ts
  packages/gamut/src/NotificationList/EmptyNotification/index.tsx
  packages/styleguide/stories/Typography/HiddenText.stories.mdx
Labels: Ship It :shipit:

#1657 feat(Dialog): Migrate to Variance + ColorModes
  packages/gamut/src/Dialog/index.tsx
  packages/styleguide/stories/Molecules/Dialog.stories.mdx
Labels: Next Release, Ship It :shipit:

#1689 fix: Circular dependency on ButtonOutline Broke focus states
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/CTAButton.tsx
  packages/gamut/src/Button/FillButton.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/StrokeButton.tsx
  packages/gamut/src/Button/TextButton.tsx
  packages/gamut/src/Button/shared.ts
Labels: Ship It :shipit:

#1692 feat: add new BinaryBlocks illustration
  packages/gamut-illustrations/src/BinaryBlocks.tsx
  packages/gamut-illustrations/src/index.ts
Labels: Ship It :shipit:

#1694 fix(Emotion): Add mode and variant to base `shouldForwardProp` filters and keep static list of all system props
  packages/gamut-styles/src/variance/utils.ts
  packages/gamut/src/Button/shared.ts
  packages/gamut/src/Logo/shared.tsx
Labels: Ship It :shipit:
