Repository Codecademy/gamut, pull requests merged in 2021-02, with the labels that each got.

#1346 fix(lint): Fix SB and Eslint config
  packages/eslint-config/index.js
  packages/styleguide/.storybook/decorators/Emotion.tsx
  packages/styleguide/.storybook/decorators/emotion.tsx
Labels: Ship It :shipit:

#1354 chore(deps): Babel and Jest resolution and updates
  .circleci/config.yml
  babel.config.js
  jest.config.js
  package.json
  packages/gamut-icons/package.json
  packages/gamut-illustrations/babel.config.js
  packages/gamut-labs/babel.config.js
  packages/gamut-labs/package.json
  packages/gamut-styles/package.json
  packages/gamut-system/package.json
  packages/gamut/babel.config.js
  packages/gamut/package.json
  packages/styleguide/.storybook/decorators/theme.tsx
  packages/styleguide/.storybook/main.ts
  packages/styleguide/__tests__/runSplitStoryshotsTests.ts
  packages/styleguide/package.json
  packages/tracking/package.json
  packages/webpack-config/package.json
  script/jest/base-setup.js
  yarn.lock
Labels: Ship It :shipit:

#1337 feat: Conversion team pairings on docs: Badge, HighlightedText, ToolTip
  packages/gamut/src/HighlightedText/index.tsx
  packages/styleguide/stories/Atoms/Badge.stories.mdx
  packages/styleguide/stories/Atoms/HighlightedText.stories.mdx
  packages/styleguide/stories/Atoms/ToolTip.stories.mdx
  packages/styleguide/stories/Atoms/TooltipArea.tsx
Labels: Auto Update, Ship It :shipit:

#1324 feat(Mobile Menu): mobile menu interactions
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLink/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/SharedStyles.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/__tests__/AppHeaderSubMenuTarget-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/styles.module.scss
  packages/gamut-labs/src/experimental/index.ts
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderDropdown.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLink.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLinkMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLogo.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMainMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderSubMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
Labels: Ship It :shipit:

#1355 feat: change LP components text color to navy
  packages/gamut-labs/src/landingPage/CTA.tsx
  packages/gamut-labs/src/landingPage/Description.tsx
  packages/gamut-labs/src/landingPage/Feature.tsx
  packages/gamut-labs/src/landingPage/Title.tsx
Labels: Ship It :shipit:

#1356 docs: standardized LP storybook pages
  packages/styleguide/stories/Brand/Organisms/PageHero.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PagePrefooter.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageVideoGallery.stories.mdx
Labels: Ship It :shipit:

#1360 chore: Update recommended VScode extensions
  .vscode/extensions.json
Labels: Ship It :shipit:

#1359 docs(Interstitial): update Interstitial documentation
  packages/gamut/src/Interstitial/index.tsx
  packages/styleguide/stories/Molecules/Interstitial.stories.mdx
Labels: Ship It :shipit:

#1349 docs(Toggle): Refresh toggle documentation
  packages/gamut/src/Toggle/index.tsx
  packages/styleguide/stories/Atoms/Toggle.stories.mdx
Labels: Ship It :shipit:

#1310 chore(dependencies): Typescript 4.1.3 [WEB-1253]
  package.json
  packages/eslint-config/package.json
  packages/gamut-labs/package.json
  packages/gamut-system/src/core/createHandler/index.ts
  packages/gamut/package.json
  packages/gamut/src/Button/CTAButton.tsx
  packages/gamut/src/GridForm/index.tsx
  packages/gamut/src/utils/createPromise.ts
  packages/prettier-config/package.json
  packages/styleguide/.storybook/addons/system/enhancers.ts
  packages/styleguide/.storybook/babel.config.js
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/.storybook/main.ts
  packages/styleguide/package.json
  packages/styleguide/tsconfig.json
  packages/tracking/package.json
  packages/webpack-config/package.json
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1340 chore(BrandMono)!: Remove Roboto Mono in favor of using Suisse
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-700.eot
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-700.svg
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-700.ttf
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-700.woff
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-700.woff2
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-regular.eot
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-regular.svg
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-regular.ttf
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-regular.woff
  packages/gamut-labs/src/brand/BrandMonospace/fonts/roboto-mono-v7-latin-regular.woff2
  packages/gamut-labs/src/brand/BrandMonospace/index.tsx
  packages/gamut-labs/src/brand/BrandMonospace/styles.module.scss
  packages/gamut-labs/src/brand/index.ts
  packages/styleguide/stories/Brand/Atoms/BrandMonospace/index.stories.mdx
  packages/styleguide/stories/Brand/Atoms/BrandMonospace/styles.module.scss
Labels: Ship It :shipit:

#1352 feat: add dark mode to video gallery and prefooter
  packages/gamut-labs/src/landingPage/CTA.tsx
  packages/gamut-labs/src/landingPage/Description.tsx
  packages/gamut-labs/src/landingPage/PagePrefooter.tsx
  packages/gamut-labs/src/landingPage/PageVideoGallery.tsx
  packages/gamut-labs/src/landingPage/Title.tsx
  packages/gamut-labs/src/landingPage/types.tsx
  packages/gamut-labs/src/landingPage/variants.tsx
  packages/styleguide/stories/Brand/Organisms/PagePrefooter.stories.mdx
  packages/styleguide/stories/Brand/Organisms/PageVideoGallery.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1363 chore: ignored js and markdown files in Codecov
  codecov.yml
Labels: Auto Update, Ship It :shipit:

#1285 feat: added gamut-tests package around component-test-setup
  jest.config.js
  package.json
  packages/gamut-labs/package.json
  packages/gamut-labs/src/landingPage/__tests__/FeaturesSection-test.tsx
  packages/gamut-tests/.gitignore
  packages/gamut-tests/README.md
  packages/gamut-tests/babel.config.js
  packages/gamut-tests/package.json
  packages/gamut-tests/src/index.tsx
  packages/gamut-tests/tsconfig.json
  packages/gamut/package.json
  packages/gamut/src/Accordion/__tests__/Accordion-test.tsx
  packages/gamut/src/AccordionArea/__tests__/AccordionArea-test.tsx
  packages/gamut/src/Pattern/__tests__/Pattern-test.tsx
  packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx
  tsconfig.json
  yarn.lock
Labels: Ship It :shipit:

#1371 style(PageHero): vertically aligned the image in page hero
  packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
Labels: Ship It :shipit:

#1362 feat: add configurable default to variants
  packages/gamut-system/docs/variants.md
  packages/gamut-system/src/core/system/__tests__/system-test.ts
  packages/gamut-system/src/core/system/index.ts
  packages/gamut-system/src/types/system.ts
Labels: Auto Update

#1374 fix: remove deprecated elseif scss syntax
  packages/gamut/src/ButtonDeprecated/styles/index.module.scss
Labels: Ship It :shipit:

#1364 refactor(PageHero): vertically centered left column and added "space" column
  packages/gamut-labs/src/landingPage/PageHero.tsx
  packages/gamut-labs/src/landingPage/PageHeroMedia.tsx
Labels: Ship It :shipit:

#1376 fix: use light variant by default
  packages/gamut-labs/src/landingPage/Description.tsx
  packages/gamut-labs/src/landingPage/Title.tsx
  packages/gamut-labs/src/landingPage/variants.tsx
Labels: Ship It :shipit:

#1378 style(Video): improved video focus outline
  packages/gamut/src/Video/styles/index.module.scss
Labels: Ship It :shipit:

#1380 fix: increase feature column gaps
  packages/gamut-labs/src/landingPage/PageFeatures.tsx
Labels: Auto Update, Ship It :shipit:

#1373 fix: added npmignore and module field for gamut-tests
  packages/gamut-tests/.npmignore
  packages/gamut-tests/package.json
Labels: Auto Update, Ship It :shipit:

#1365 fix: add event parameter to landing page CTA onClick
  packages/gamut-labs/src/landingPage/CTA.tsx
  packages/gamut-labs/src/landingPage/types.tsx
Labels: Ship It :shipit:

#1383 fix(AccordionButton): bump specificity of accordion button styles
  packages/gamut/src/AccordionButton/styles.module.scss
Labels: Ship It :shipit:

#1387 revert: fix(AccordionButton) bump specificity of accordion button styles
  packages/gamut/src/AccordionButton/styles.module.scss
Labels: Ship It :shipit:

#1367 feat(Mobile Menu Variants): global header mobile
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderAvatar/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLinkSections/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/SharedStyles.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/experimental/AppHeader/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/types.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/__tests__/AppHeaderSubMenuTarget-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/__tests__/AppHeaderMobile-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/styles.module.scss
  packages/gamut-labs/src/experimental/GlobalHeader/types.tsx
  packages/gamut-labs/src/experimental/index.ts
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderDropdown.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMainMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderSubMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/MockAppHeaderElements.tsx
Labels: Ship It :shipit:

#1391 fix(catalog link): copy should catalog, not course catalog
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderLinkMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/GlobalHeaderItems.tsx
Labels: Ship It :shipit:

#1384 fix: update font sizes within LP components at smaller than xs
  packages/gamut-labs/src/landingPage/Feature.tsx
  packages/gamut-labs/src/landingPage/Title.tsx
Labels: Ship It :shipit:

#1393 fix(GlobalHeader): Spacing fixes
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderTab/index.tsx
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/SharedStyles.tsx
  packages/gamut-labs/src/experimental/AppHeader/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
Labels: Ship It :shipit:

#1386 fix(Toggle): remove aria-label
  packages/gamut/src/Toggle/index.tsx
Labels: Ship It :shipit:

#1233 feat: imported babel plugin
  package.json
  packages/babel-preset-codecademy/README.md
  packages/babel-preset-codecademy/index.js
  packages/babel-preset-codecademy/package.json
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1397 fix: reduce column gaps on mobile for LP components
  packages/gamut-labs/src/landingPage/PageFeatures.tsx
  packages/gamut-labs/src/landingPage/PageHero.tsx
Labels: Ship It :shipit:

#1401 feat: adding 3 new icons for business reporting
  packages/gamut-icons/src/svg/regular/data-file-bars-share-icon.svg
  packages/gamut-icons/src/svg/regular/data-transfer-vertical-icon.svg
  packages/gamut-icons/src/svg/regular/settings-slider-vertical-icon.svg
Labels: Ship It :shipit:

#1326 feat!: bumped ESLint packages to latest and added recommended & Jest linting
  .eslintrc.js
  jest.config.js
  package.json
  packages/babel-preset-codecademy/index.js
  packages/eslint-config/bin/eslint-fix.js
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/rules/mdx.js
  packages/eslint-config/rules/typescript.js
  packages/gamut-labs/src/experimental/AppHeader/AppHeaderElements/AppHeaderLogo/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/__tests__/AppHeaderMainMenuMobile-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuMobile/__tests__/AppHeaderSubMenuMobile-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/__tests__/AppHeaderSubMenuTarget-test.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut-labs/src/experimental/Popover/__tests__/Popover-test.tsx
  packages/gamut-labs/src/landingPage/PageFeatures.tsx
  packages/gamut-labs/src/landingPage/PageHero.tsx
  packages/gamut-labs/src/landingPage/PagePrefooter.tsx
  packages/gamut-labs/src/landingPage/PageVideoGallery.tsx
  packages/gamut-styles/src/variables/deprecated-colors.ts
  packages/gamut-styles/src/variables/shadows.ts
  packages/gamut-system/src/core/compose/__tests__/compose-test.ts
  packages/gamut-system/src/core/createHandler/__tests__/createHandler-test.ts
  packages/gamut-system/src/styleTemplates/createResponsiveStyleTemplate/__tests__/createResponsiveStyleTemplate-test.ts
  packages/gamut-system/src/styleTemplates/createResponsiveStyleTemplate/index.ts
  packages/gamut-system/src/transforms/parseSize/index.ts
  packages/gamut-tests/dist/index.d.ts
  packages/gamut-tests/dist/index.js
  packages/gamut/src/Alert/index.tsx
  packages/gamut/src/ButtonDeprecatedBase/index.tsx
  packages/gamut/src/FlexBox/Container.tsx
  packages/gamut/src/FlexBox/Item.tsx
  packages/gamut/src/FlexGrid/Row.tsx
  packages/gamut/src/Form/Checkbox.tsx
  packages/gamut/src/Form/RadioGroup.tsx
  packages/gamut/src/GridForm/__tests__/GridForm-test.tsx
  packages/gamut/src/InputStepper/__tests__/Stepper-test.tsx
  packages/gamut/src/InputStepper/index.tsx
  packages/gamut/src/Markdown/index.tsx
  packages/gamut/src/Markdown/libs/preprocessing.ts
  packages/gamut/src/NotificationList/index.tsx
  packages/gamut/src/Overlay/__tests__/Overlay-test.tsx
  packages/macros/__tests__/macros.test.js
  packages/macros/example/stories/World/Example.stories.js
  packages/macros/example/stories/World/Hello.js
  packages/macros/lib/title.macro.js
  packages/markdown-overrides/src/ErrorBlock/__tests__/ErrorBlock-test.tsx
  packages/markdown-overrides/src/MathBlock/__tests__/MathBlock-test.tsx
  packages/markdown-overrides/src/PseudoBlock/__tests__/PseudoBlock-test.tsx
  packages/styleguide/stories/Atoms/ButtonDeprecated/helpers.tsx
  packages/styleguide/stories/Atoms/FormInputs/Checkbox.stories.mdx
  packages/styleguide/stories/Atoms/Popover/Popover.examples.tsx
  packages/styleguide/stories/Molecules/Accordion.stories.mdx
  packages/styleguide/stories/Molecules/AppBar.stories.mdx
  packages/webpack-config/src/config/css-extracted.js
  packages/webpack-config/src/index.js
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1398 fix(GlobalHeader): Simplify loading header
  packages/gamut-labs/src/experimental/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/experimental/GlobalHeader/index.tsx
Labels: Ship It :shipit:

#1366 fix(Markdown): Relative <code> fontSize [TR2-440]
  packages/gamut/src/Markdown/styles/_mixins.scss
Labels: Ship It :shipit:

#1395 feat(Styleguide): Gamut System docs and routing fixes
  packages/gamut-system/docs/variants.md
  packages/styleguide/.storybook/addons/system/enhancers.ts
  packages/styleguide/.storybook/components/Page/index.tsx
  packages/styleguide/.storybook/components/PropsTable/Elements.tsx
  packages/styleguide/.storybook/components/PropsTable/index.tsx
  packages/styleguide/.storybook/components/TableOfContents/Section.tsx
  packages/styleguide/.storybook/components/TableOfContents/elements.tsx
  packages/styleguide/.storybook/components/TableOfContents/utils.tsx
  packages/styleguide/.storybook/components/styles.ts
  packages/styleguide/.storybook/components/utils.ts
  packages/styleguide/.storybook/preview.ts
  packages/styleguide/stories/Foundations/Layout.stories.mdx
  packages/styleguide/stories/Foundations/System/About.stories.mdx
  packages/styleguide/stories/Foundations/System/Compose.stories.mdx
  packages/styleguide/stories/Foundations/System/Props.stories.mdx
  packages/styleguide/stories/Foundations/System/Responsive Properties.stories.mdx
  packages/styleguide/stories/Foundations/System/Variants.stories.mdx
  packages/styleguide/stories/Foundations/Typography.stories.mdx
  packages/styleguide/stories/Foundations/Utilities.stories.mdx
Labels: Ship It :shipit:

#1351 docs: updates to Banner, ContentContainer, LayoutGrid, RadialProgress, SkipToContent, Text
  packages/styleguide/stories/Atoms/RadialProgress.stories.mdx
  packages/styleguide/stories/Atoms/SkipToContent.stories.mdx
  packages/styleguide/stories/Foundations/Layout.stories.mdx
  packages/styleguide/stories/Layouts/ContentContainer.stories.mdx
  packages/styleguide/stories/Layouts/LayoutGrid.stories.mdx
  packages/styleguide/stories/Molecules/Banner.stories.mdx
  packages/styleguide/stories/Typography/Text.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1368 fix: used 'sanitize-markdown' fork of 'insane'
  packages/gamut/package.json
  packages/gamut/src/Markdown/__tests__/Markdown-test.tsx
  packages/gamut/src/Markdown/index.tsx
  packages/gamut/src/Markdown/libs/sanitizationConfig.ts
  packages/gamut/src/typings/insane.d.ts
  packages/gamut/src/typings/sanitize-markdown.ts
  yarn.lock
Labels: Auto Update, Ship It :shipit:

#1388 feat: allowed disabled inputs for GridForm
  packages/gamut/src/Form/FormGroupLabel.tsx
  packages/gamut/src/Form/styles/FormGroupLabel.module.scss
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormCheckboxInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormFileInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormRadioGroupInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormSelectInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextArea/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/GridFormTextInput/index.tsx
  packages/gamut/src/GridForm/GridFormInputGroup/index.tsx
  packages/gamut/src/GridForm/types.ts
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
Labels: Auto Update, Ship It :shipit:

#1413 feat(Button): Alternative (secondary) modes and consistent height [GM-126]
  packages/gamut-styles/src/variables/colors.ts
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/CTAButton.tsx
  packages/gamut/src/Button/FillButton.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/gamut/src/Button/StrokeButton.tsx
  packages/gamut/src/Button/TextButton.tsx
  packages/gamut/src/Button/shared.ts
  packages/styleguide/stories/Atoms/Button/examples.tsx
  packages/styleguide/stories/Atoms/Button/index.stories.mdx
  yarn.lock
Labels: Ship It :shipit:

#1382 feat!: progress bar theme => variant
  packages/gamut/src/ProgressBar/__tests__/ProgressBar-test.tsx
  packages/gamut/src/ProgressBar/index.tsx
  packages/gamut/src/ProgressBar/styles.module.scss
  packages/styleguide/stories/Atoms/ProgressBar/constants.tsx
  packages/styleguide/stories/Atoms/ProgressBar/index.stories.mdx
Labels: Ship It :shipit:

#1420 feat: add container_slugs to UserClickData tracking type
  packages/tracking/src/types.ts
Labels: Ship It :shipit:

#1411 feat(Banner)!: Banner new visual identity [GM-123]
  packages/gamut-icons/src/svg/mini/mini-delete-icon.svg
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/src/Banner/__tests__/Banner-test.tsx
  packages/gamut/src/Banner/index.tsx
  packages/gamut/src/Banner/styles.module.scss
  packages/gamut/src/Button/ButtonOutline.tsx
  packages/gamut/src/Button/IconButton.tsx
  packages/styleguide/stories/Molecules/Banner.stories.mdx
Labels: Ship It :shipit:

#1385 feat: add new coachmark component
  packages/gamut-labs/src/experimental/Coachmark/__tests__/Coachmark-test.tsx
  packages/gamut-labs/src/experimental/Coachmark/index.tsx
  packages/gamut-labs/src/experimental/Popover/__tests__/Popover-test.tsx
  packages/gamut-labs/src/experimental/Popover/index.tsx
  packages/gamut-labs/src/experimental/Popover/styles.module.scss
  packages/gamut-labs/src/experimental/index.ts
  packages/styleguide/.storybook/getStories.ts
  packages/styleguide/stories/Atoms/Popover/Popover.examples.tsx
  packages/styleguide/stories/Atoms/Popover/index.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/Coachmark/Coachmark.examples.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Coachmark/index.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/index.stories.mdx
Labels: Ship It :shipit:

#1424 fix: popover pattern expands to the size of its container
  packages/gamut-labs/src/experimental/Popover/index.tsx
Labels: Ship It :shipit:

#1427 test: add gamut-illustrations to test/styleguide alias configs
  jest.config.js
  packages/styleguide/.storybook/main.ts
Labels: Ship It :shipit:

#1418 feat(New Notifications components): notifications list & notification
  packages/gamut-illustrations/package.json
  packages/gamut-illustrations/src/Bell.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut/__tests__/__snapshots__/gamut-test.ts.snap
  packages/gamut/package.json
  packages/gamut/src/NotificationListNew/NotificationItemNew.tsx
  packages/gamut/src/NotificationListNew/__tests__/NotificationItemNew-test.tsx
  packages/gamut/src/NotificationListNew/__tests__/NotificationListNew-test.tsx
  packages/gamut/src/NotificationListNew/index.tsx
  packages/gamut/src/Pattern/index.tsx
  packages/gamut/src/index.tsx
  packages/styleguide/stories/Molecules/NotificationList.stories.mdx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1426 docs(GlobalHeader): Polish GlobalHeader / AppHeader docs
  packages/styleguide/stories/Labs/Experimental/Molecules/About.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeader.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderDropdown.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLink.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLinkMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderLogo.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMainMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/AppHeaderSubMenuMobile.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/GlobalHeader.stories.mdx
  packages/styleguide/stories/Labs/Experimental/Molecules/MockAppHeaderElements.tsx
Labels: Ship It :shipit:

#1425 fix: remove z index from popover
  packages/gamut-labs/src/experimental/Popover/index.tsx
Labels: Ship It :shipit:

#1423 feat: add a illustration for business team
  packages/gamut-illustrations/src/Onboarding.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut-tests/dist/index.d.ts
Labels: Auto Update, Ship It :shipit:

#1429 fix(NotificationListNew): Key and spacing issues
  packages/gamut/src/NotificationListNew/index.tsx
Labels: Ship It :shipit:

#1421 fix: TOC links
  packages/styleguide/.storybook/components/TableOfContents/utils.tsx
Labels: Ship It :shipit:

#1422 feat(NotificationListNew): add empty notification
  packages/gamut-illustrations/src/Bee.tsx
  packages/gamut-illustrations/src/Browser.tsx
  packages/gamut-illustrations/src/Confetti.tsx
  packages/gamut-illustrations/src/Plant.tsx
  packages/gamut-illustrations/src/Sun.tsx
  packages/gamut-illustrations/src/index.ts
  packages/gamut/src/NotificationListNew/EmptyNotification/emptyNotificationContents.tsx
  packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
  packages/gamut/src/NotificationListNew/__tests__/NotificationListNew-test.tsx
  packages/gamut/src/NotificationListNew/index.tsx
  packages/styleguide/stories/Molecules/NotificationListNew.stories.mdx
Labels: Ship It :shipit:

#1431 fix(Button): fix negligent selectors
  packages/gamut/src/Button/ButtonInner.tsx
  packages/gamut/src/Button/IconButton.tsx
Labels: Ship It :shipit:

#1396 fix(emotion): Cache changes
  package.json
  packages/gamut-styles/src/cache/index.ts
  yarn.lock
Labels: Ship It :shipit:

#1432 ci: add auto assign reviewers config
  .github/reviewers.yml
  .github/workflows/auto-request-review.yml
Labels: Ship It :shipit:

#1433 fix(app header mobile & notifs empty container): add + fix test ids
  packages/gamut-labs/src/experimental/AppHeaderMobile/index.tsx
  packages/gamut/src/NotificationListNew/EmptyNotification/index.tsx
Labels: Ship It :shipit:

#1415 feat: add linting for gamut imports
  .eslintrc.js
  eslint-local-rules.js
  eslint/gamut-import-paths.js
  package.json
  packages/gamut-labs/src/experimental/AppHeaderMobile/AppHeaderSubMenuTarget/__tests__/AppHeaderSubMenuTarget-test.tsx
  packages/gamut-labs/src/experimental/index.ts
  packages/styleguide/stories/Atoms/Button/examples.tsx
  packages/styleguide/stories/Atoms/ButtonDeprecated/helpers.tsx
  packages/styleguide/stories/Atoms/Icons/constants.tsx
  packages/styleguide/stories/Atoms/Markdown/examples.tsx
  packages/styleguide/stories/Atoms/TooltipArea.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Coachmark/Coachmark.examples.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/MockAppHeaderElements.tsx
  packages/styleguide/stories/Labs/Experimental/Molecules/Popover/Popover.examples.tsx
  packages/styleguide/stories/Layouts/Elements/index.tsx
  yarn.lock
Labels: Ship It :shipit:

#1435 fix(video): include wrapper in type
  packages/gamut/src/Video/index.tsx
Labels: Ship It :shipit:

#1419 fix: use separate eslint-fix config
  package.json
  packages/eslint-config/bin/eslint-fix.js
  packages/eslint-config/fix.js
  packages/eslint-config/rules/typescript.js
Labels: Ship It :shipit:
