Repository Codecademy/gamut, pull requests merged in 2022-04, with the labels that each got.

#2303 feat(FromLogo): add logo
  packages/gamut-labs/src/LogoFromSkillsoft/index.tsx
  packages/gamut-labs/src/index.ts
Labels: Ship It :shipit:

#2298 feat(ConnectedForm): Exports clearErrors from rhf
  packages/gamut/src/ConnectedForm/utils.tsx
Labels: Ship It :shipit:

#2308 fix(GlobalHeader): fixing tab issue with GlobalHeader
  packages/gamut-labs/src/Notifications/NotificationBell.tsx
  packages/gamut-labs/src/Notifications/__tests__/NotificationBell-test.tsx
  packages/gamut-labs/src/Notifications/__tests__/useHeaderNotifications-test.tsx
Labels: Auto Update

#2305 fix(GlobalHeader): Pass user to all anon header items
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
Labels: Ship It :shipit:

#2309 refactor(Footer + FromSkillsoftLogo): clean up + add story
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
  packages/gamut-labs/src/GlobalFooter/__tests__/GlobalFooter-test.tsx
  packages/gamut-labs/src/GlobalFooter/index.tsx
  packages/gamut-labs/src/GlobalPage/__tests__/GlobalPage-test.tsx
  packages/gamut-labs/src/LogoFromSkillsoft/index.tsx
  packages/styleguide/stories/Atoms/LogoFromSkillsoft/LogoFromSkillsoft.stories.mdx
  packages/styleguide/stories/Molecules/GlobalFooter.stories.mdx
Labels: Ship It :shipit:

#2314 docs: code snippet updates
  .vscode/stories.code-snippets
Labels: Ship It :shipit:

#2311 feat(AppHeaderCatalogDropdown): added AppHeaderCatalogDropdown component
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderDropdown/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/types.tsx
  packages/gamut-labs/src/AppHeader/index.tsx
  packages/gamut-labs/src/AppHeader/shared.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderMainMenuMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuMobile/index.tsx
  packages/gamut-labs/src/AppHeaderMobile/AppHeaderSubMenuTarget/index.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderVariants.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/GlobalHeader/index.tsx
  packages/gamut-labs/src/lib/catalogList/index.tsx
Labels: Ship It :shipit:

#2304 feat(HorizontalScrollBar): added Horizontal Scrollbar component
  packages/gamut-labs/src/HorizontalScrollMenu/index.tsx
  packages/gamut-labs/src/index.ts
  packages/styleguide/stories/Molecules/HorizontalScrollMenu/HorizontalScrollMenu.examples.tsx
  packages/styleguide/stories/Molecules/HorizontalScrollMenu/index.stories.mdx
Labels: Ship It :shipit:

#2313 feat(SocialMediaSharing): making SocialMediaSharing responsive to colormode
  packages/gamut-labs/src/GlobalFooter/index.tsx
  packages/gamut-labs/src/SocialMediaSharing/SocialShareIconLink.tsx
  packages/gamut-labs/src/SocialMediaSharing/index.tsx
  packages/gamut-styles/src/ColorMode.tsx
  packages/styleguide/stories/Foundations/ColorMode/examples.tsx
  packages/styleguide/stories/Foundations/ColorMode/index.stories.mdx
  packages/styleguide/stories/Molecules/SocialMediaSharing.stories.mdx
Labels: Ship It :shipit:, Auto Update

#2320 fix(AppHeaderCatalogSection): hot fix for CI failures
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
Labels: Ship It :shipit:

#2318 feat(GlobalHeaderItems): Business Sso check for profile
  packages/gamut-labs/src/GlobalHeader/GlobalHeaderItems.tsx
  packages/gamut-labs/src/GlobalHeader/types.tsx
Labels: Ship It :shipit:

#2290 fix(Alert): Remove unused alert type
  packages/gamut/src/Alert/Alert.tsx
Labels: Ship It :shipit:

#2327 test(AppHeaderCatalogDropdown): add unit tests for resources and catalog dropdown items
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
  packages/gamut-labs/src/GlobalHeader/__tests__/GlobalHeader-test.tsx
  packages/gamut-labs/src/lib/catalogList/__tests__/index-test.tsx
  packages/gamut-labs/src/lib/resourcesList/__tests__/index-test.tsx
Labels: Ship It :shipit:

#2321 fix(HorizontalScrollMenu): fixed axe issue with hidden elements receiving focus
  packages/gamut-labs/src/HorizontalScrollMenu/index.tsx
Labels: Ship It :shipit:

#2329 feat(GlobalFooter): Add Extole marketing anchor
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Ship It :shipit:

#2326 feat(AppHeaderCatalogDropdown): adding keyboard functionality
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/__tests__/AppHeaderCatalogDropdown-test.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogDropdown/index.tsx
  packages/gamut-labs/src/AppHeader/AppHeaderElements/AppHeaderCatalogSection/index.tsx
Labels: Ship It :shipit:

#2331 docs: proposed changes to PR templates
  .github/pull_request_template.md
Labels: Ship It :shipit:

#2330 fix(CompanyLinks): Wrap extole zone in a footer item
  packages/gamut-labs/src/GlobalFooter/FooterNavLinks/CompanyLinks.tsx
Labels: Ship It :shipit:

#2288 feat(Toggle)!: colors, labels, + elements
  packages/gamut/src/Toggle/__tests__/Toggle-test.tsx
  packages/gamut/src/Toggle/elements.tsx
  packages/gamut/src/Toggle/index.tsx
  packages/gamut/src/Toggle/types.tsx
  packages/gamut/src/Toggle/utils.tsx
  packages/styleguide/stories/Atoms/Toggle.examples.tsx
  packages/styleguide/stories/Atoms/Toggle.stories.mdx
Labels: Ship It :shipit:

#2334 feat(release notes): test slack bot notifs
  .github/workflows/announce-release.yml
Labels: Ship It :shipit:

#2338 docs(GridForm): update ColorMode docs
  packages/styleguide/stories/Organisms/GridForm.stories.mdx
  packages/styleguide/stories/Organisms/examples.tsx
Labels: Ship It :shipit:

#2339 ci: tweak automerge regex
  .github/workflows/automerge.yml
  packages/styleguide/stories/Atoms/Button/index.stories.mdx
Labels: Ship It :shipit:

#2340 feat(Test): isolate body output markdown
  .github/workflows/announce-release.yml
  packages/gamut/src/Badge/index.tsx
Labels: Ship It :shipit:
